// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v5.29.3
// source: ledger/ledger.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Order } from "../common/order";

export const protobufPackage = "ledger";

export interface RecordOrderRequest {
  order?: Order | undefined;
}

export interface RecordOrderResponse {
  transactionId?: string | undefined;
  success?: boolean | undefined;
  message?: string | undefined;
}

function createBaseRecordOrderRequest(): RecordOrderRequest {
  return { order: undefined };
}

export const RecordOrderRequest: MessageFns<RecordOrderRequest> = {
  encode(message: RecordOrderRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.order !== undefined) {
      Order.encode(message.order, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecordOrderRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecordOrderRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.order = Order.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RecordOrderRequest {
    return { order: isSet(object.order) ? Order.fromJSON(object.order) : undefined };
  },

  toJSON(message: RecordOrderRequest): unknown {
    const obj: any = {};
    if (message.order !== undefined) {
      obj.order = Order.toJSON(message.order);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RecordOrderRequest>, I>>(base?: I): RecordOrderRequest {
    return RecordOrderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RecordOrderRequest>, I>>(object: I): RecordOrderRequest {
    const message = createBaseRecordOrderRequest();
    message.order = (object.order !== undefined && object.order !== null) ? Order.fromPartial(object.order) : undefined;
    return message;
  },
};

function createBaseRecordOrderResponse(): RecordOrderResponse {
  return { transactionId: "", success: false, message: "" };
}

export const RecordOrderResponse: MessageFns<RecordOrderResponse> = {
  encode(message: RecordOrderResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transactionId !== undefined && message.transactionId !== "") {
      writer.uint32(10).string(message.transactionId);
    }
    if (message.success !== undefined && message.success !== false) {
      writer.uint32(16).bool(message.success);
    }
    if (message.message !== undefined && message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RecordOrderResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecordOrderResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.transactionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RecordOrderResponse {
    return {
      transactionId: isSet(object.transactionId)
        ? globalThis.String(object.transactionId)
        : isSet(object.transaction_id)
        ? globalThis.String(object.transaction_id)
        : "",
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: RecordOrderResponse): unknown {
    const obj: any = {};
    if (message.transactionId !== undefined && message.transactionId !== "") {
      obj.transactionId = message.transactionId;
    }
    if (message.success !== undefined && message.success !== false) {
      obj.success = message.success;
    }
    if (message.message !== undefined && message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RecordOrderResponse>, I>>(base?: I): RecordOrderResponse {
    return RecordOrderResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RecordOrderResponse>, I>>(object: I): RecordOrderResponse {
    const message = createBaseRecordOrderResponse();
    message.transactionId = object.transactionId ?? "";
    message.success = object.success ?? false;
    message.message = object.message ?? "";
    return message;
  },
};

export type LedgerServiceService = typeof LedgerServiceService;
export const LedgerServiceService = {
  recordOrder: {
    path: "/ledger.LedgerService/RecordOrder",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RecordOrderRequest): Buffer => Buffer.from(RecordOrderRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RecordOrderRequest => RecordOrderRequest.decode(value),
    responseSerialize: (value: RecordOrderResponse): Buffer => Buffer.from(RecordOrderResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RecordOrderResponse => RecordOrderResponse.decode(value),
  },
} as const;

export interface LedgerServiceServer extends UntypedServiceImplementation {
  recordOrder: handleUnaryCall<RecordOrderRequest, RecordOrderResponse>;
}

export interface LedgerServiceClient extends Client {
  recordOrder(
    request: RecordOrderRequest,
    callback: (error: ServiceError | null, response: RecordOrderResponse) => void,
  ): ClientUnaryCall;
  recordOrder(
    request: RecordOrderRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RecordOrderResponse) => void,
  ): ClientUnaryCall;
  recordOrder(
    request: RecordOrderRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RecordOrderResponse) => void,
  ): ClientUnaryCall;
}

export const LedgerServiceClient = makeGenericClientConstructor(
  LedgerServiceService,
  "ledger.LedgerService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): LedgerServiceClient;
  service: typeof LedgerServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
