// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v5.29.3
// source: market/market.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "market";

export interface SubscribePricesRequest {
  symbol?: string | undefined;
}

export interface GetLatestPriceRequest {
  symbol?: string | undefined;
}

export interface PriceUpdate {
  symbol?: string | undefined;
  price?: string | undefined;
  timestamp?: string | undefined;
  change24h?: number | undefined;
  volume24h?: number | undefined;
}

function createBaseSubscribePricesRequest(): SubscribePricesRequest {
  return { symbol: "" };
}

export const SubscribePricesRequest: MessageFns<SubscribePricesRequest> = {
  encode(message: SubscribePricesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== undefined && message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscribePricesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscribePricesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubscribePricesRequest {
    return { symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "" };
  },

  toJSON(message: SubscribePricesRequest): unknown {
    const obj: any = {};
    if (message.symbol !== undefined && message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubscribePricesRequest>, I>>(base?: I): SubscribePricesRequest {
    return SubscribePricesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubscribePricesRequest>, I>>(object: I): SubscribePricesRequest {
    const message = createBaseSubscribePricesRequest();
    message.symbol = object.symbol ?? "";
    return message;
  },
};

function createBaseGetLatestPriceRequest(): GetLatestPriceRequest {
  return { symbol: "" };
}

export const GetLatestPriceRequest: MessageFns<GetLatestPriceRequest> = {
  encode(message: GetLatestPriceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== undefined && message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetLatestPriceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetLatestPriceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetLatestPriceRequest {
    return { symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "" };
  },

  toJSON(message: GetLatestPriceRequest): unknown {
    const obj: any = {};
    if (message.symbol !== undefined && message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetLatestPriceRequest>, I>>(base?: I): GetLatestPriceRequest {
    return GetLatestPriceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetLatestPriceRequest>, I>>(object: I): GetLatestPriceRequest {
    const message = createBaseGetLatestPriceRequest();
    message.symbol = object.symbol ?? "";
    return message;
  },
};

function createBasePriceUpdate(): PriceUpdate {
  return { symbol: "", price: "", timestamp: "0", change24h: 0, volume24h: 0 };
}

export const PriceUpdate: MessageFns<PriceUpdate> = {
  encode(message: PriceUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.symbol !== undefined && message.symbol !== "") {
      writer.uint32(10).string(message.symbol);
    }
    if (message.price !== undefined && message.price !== "") {
      writer.uint32(18).string(message.price);
    }
    if (message.timestamp !== undefined && message.timestamp !== "0") {
      writer.uint32(24).int64(message.timestamp);
    }
    if (message.change24h !== undefined && message.change24h !== 0) {
      writer.uint32(33).double(message.change24h);
    }
    if (message.volume24h !== undefined && message.volume24h !== 0) {
      writer.uint32(41).double(message.volume24h);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PriceUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePriceUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.symbol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.price = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timestamp = reader.int64().toString();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.change24h = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.volume24h = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PriceUpdate {
    return {
      symbol: isSet(object.symbol) ? globalThis.String(object.symbol) : "",
      price: isSet(object.price) ? globalThis.String(object.price) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "0",
      change24h: isSet(object.change24h)
        ? globalThis.Number(object.change24h)
        : isSet(object.change_24h)
        ? globalThis.Number(object.change_24h)
        : 0,
      volume24h: isSet(object.volume24h)
        ? globalThis.Number(object.volume24h)
        : isSet(object.volume_24h)
        ? globalThis.Number(object.volume_24h)
        : 0,
    };
  },

  toJSON(message: PriceUpdate): unknown {
    const obj: any = {};
    if (message.symbol !== undefined && message.symbol !== "") {
      obj.symbol = message.symbol;
    }
    if (message.price !== undefined && message.price !== "") {
      obj.price = message.price;
    }
    if (message.timestamp !== undefined && message.timestamp !== "0") {
      obj.timestamp = message.timestamp;
    }
    if (message.change24h !== undefined && message.change24h !== 0) {
      obj.change24h = message.change24h;
    }
    if (message.volume24h !== undefined && message.volume24h !== 0) {
      obj.volume24h = message.volume24h;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PriceUpdate>, I>>(base?: I): PriceUpdate {
    return PriceUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PriceUpdate>, I>>(object: I): PriceUpdate {
    const message = createBasePriceUpdate();
    message.symbol = object.symbol ?? "";
    message.price = object.price ?? "";
    message.timestamp = object.timestamp ?? "0";
    message.change24h = object.change24h ?? 0;
    message.volume24h = object.volume24h ?? 0;
    return message;
  },
};

export type MarketServiceService = typeof MarketServiceService;
export const MarketServiceService = {
  /** Streams real-time price updates for a given symbol */
  subscribePrices: {
    path: "/market.MarketService/SubscribePrices",
    requestStream: false,
    responseStream: true,
    requestSerialize: (value: SubscribePricesRequest): Buffer =>
      Buffer.from(SubscribePricesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SubscribePricesRequest => SubscribePricesRequest.decode(value),
    responseSerialize: (value: PriceUpdate): Buffer => Buffer.from(PriceUpdate.encode(value).finish()),
    responseDeserialize: (value: Buffer): PriceUpdate => PriceUpdate.decode(value),
  },
  /** Gets the latest snapshot for a symbol */
  getLatestPrice: {
    path: "/market.MarketService/GetLatestPrice",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetLatestPriceRequest): Buffer =>
      Buffer.from(GetLatestPriceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetLatestPriceRequest => GetLatestPriceRequest.decode(value),
    responseSerialize: (value: PriceUpdate): Buffer => Buffer.from(PriceUpdate.encode(value).finish()),
    responseDeserialize: (value: Buffer): PriceUpdate => PriceUpdate.decode(value),
  },
} as const;

export interface MarketServiceServer extends UntypedServiceImplementation {
  /** Streams real-time price updates for a given symbol */
  subscribePrices: handleServerStreamingCall<SubscribePricesRequest, PriceUpdate>;
  /** Gets the latest snapshot for a symbol */
  getLatestPrice: handleUnaryCall<GetLatestPriceRequest, PriceUpdate>;
}

export interface MarketServiceClient extends Client {
  /** Streams real-time price updates for a given symbol */
  subscribePrices(request: SubscribePricesRequest, options?: Partial<CallOptions>): ClientReadableStream<PriceUpdate>;
  subscribePrices(
    request: SubscribePricesRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<PriceUpdate>;
  /** Gets the latest snapshot for a symbol */
  getLatestPrice(
    request: GetLatestPriceRequest,
    callback: (error: ServiceError | null, response: PriceUpdate) => void,
  ): ClientUnaryCall;
  getLatestPrice(
    request: GetLatestPriceRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: PriceUpdate) => void,
  ): ClientUnaryCall;
  getLatestPrice(
    request: GetLatestPriceRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: PriceUpdate) => void,
  ): ClientUnaryCall;
}

export const MarketServiceClient = makeGenericClientConstructor(
  MarketServiceService,
  "market.MarketService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): MarketServiceClient;
  service: typeof MarketServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
