export const assetsData = [
  { symbol: 'USD', name: 'US Dollar', klass: 'fiat', decimals: 2 },
  // Cryptos
  {
    symbol: 'USDT',
    name: 'Tether',
    klass: 'crypto',
    decimals: 6,
    meta: { circulatingSupply: 183746512716 },
  },
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    klass: 'crypto',
    decimals: 8,
    meta: { circulatingSupply: 19_992_382 },
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    klass: 'crypto',
    decimals: 18,
    meta: { circulatingSupply: 120692664 },
  },
  {
    symbol: 'BNB',
    name: 'BNB',
    klass: 'crypto',
    decimals: 18,
    meta: { circulatingSupply: 136359935 },
  },
  {
    symbol: 'SOL',
    name: 'Solana',
    klass: 'crypto',
    decimals: 9,
    meta: { circulatingSupply: 568407358 },
  },
  {
    symbol: 'XRP',
    name: 'XRP',
    klass: 'crypto',
    decimals: 6,
    meta: { circulatingSupply: 61052860348 },
  },
  {
    symbol: 'USDC',
    name: 'USDC',
    klass: 'crypto',
    decimals: 6,
    meta: { circulatingSupply: 74367369734 },
  },
  {
    symbol: 'ADA',
    name: 'Cardano',
    klass: 'crypto',
    decimals: 6,
    meta: { circulatingSupply: 36078443710 },
  },
  {
    symbol: 'AVAX',
    name: 'Avalanche',
    klass: 'crypto',
    decimals: 18,
    meta: { circulatingSupply: 431554393 },
  },
  {
    symbol: 'DOGE',
    name: 'Dogecoin',
    klass: 'crypto',
    decimals: 8,
    meta: { circulatingSupply: 168879636791 },
  },
  {
    symbol: 'OPENC',
    name: 'Open Coin',
    klass: 'crypto',
    decimals: 18,
    meta: { circulatingSupply: 100000000 },
  },
  // Stocks
  { symbol: 'AAPL', name: 'Apple Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'MSFT', name: 'Microsoft Corp.', klass: 'stock', decimals: 2 },
  { symbol: 'GOOGL', name: 'Alphabet Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'NVDA', name: 'NVIDIA Corp.', klass: 'stock', decimals: 2 },
  {
    symbol: 'META',
    name: 'Meta Platforms Inc.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'TSLA', name: 'Tesla Inc.', klass: 'stock', decimals: 2 },
  {
    symbol: 'BRK.B',
    name: 'Berkshire Hathaway Inc.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'LLY', name: 'Eli Lilly and Co.', klass: 'stock', decimals: 2 },
  { symbol: 'V', name: 'Visa Inc.', klass: 'stock', decimals: 2 },
  {
    symbol: 'JPM',
    name: 'JPMorgan Chase & Co.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'AVGO', name: 'Broadcom Inc.', klass: 'stock', decimals: 2 },
  {
    symbol: 'UNH',
    name: 'UnitedHealth Group Inc.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'WMT', name: 'Walmart Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'MA', name: 'Mastercard Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'XOM', name: 'Exxon Mobil Corp.', klass: 'stock', decimals: 2 },
  { symbol: 'JNJ', name: 'Johnson & Johnson', klass: 'stock', decimals: 2 },
  { symbol: 'PG', name: 'Procter & Gamble Co.', klass: 'stock', decimals: 2 },
  { symbol: 'HD', name: 'Home Depot Inc.', klass: 'stock', decimals: 2 },
  {
    symbol: 'COST',
    name: 'Costco Wholesale Corp.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'MRK', name: 'Merck & Co. Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'ORCL', name: 'Oracle Corp.', klass: 'stock', decimals: 2 },
  { symbol: 'ABBV', name: 'AbbVie Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'CVX', name: 'Chevron Corp.', klass: 'stock', decimals: 2 },
  {
    symbol: 'BAC',
    name: 'Bank of America Corp.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'ADBE', name: 'Adobe Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'CRM', name: 'Salesforce Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'KO', name: 'Coca-Cola Co.', klass: 'stock', decimals: 2 },
  {
    symbol: 'AMD',
    name: 'Advanced Micro Devices Inc.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'PEP', name: 'PepsiCo Inc.', klass: 'stock', decimals: 2 },
  {
    symbol: 'TMO',
    name: 'Thermo Fisher Scientific Inc.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'NFLX', name: 'Netflix Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'MCD', name: "McDonald's Corp.", klass: 'stock', decimals: 2 },
  { symbol: 'LIN', name: 'Linde plc', klass: 'stock', decimals: 2 },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'WFC', name: 'Wells Fargo & Co.', klass: 'stock', decimals: 2 },
  { symbol: 'ACN', name: 'Accenture plc', klass: 'stock', decimals: 2 },
  { symbol: 'ABT', name: 'Abbott Laboratories', klass: 'stock', decimals: 2 },
  { symbol: 'DHR', name: 'Danaher Corp.', klass: 'stock', decimals: 2 },
  { symbol: 'INTU', name: 'Intuit Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'DIS', name: 'Walt Disney Co.', klass: 'stock', decimals: 2 },
  { symbol: 'NKE', name: 'NIKE Inc.', klass: 'stock', decimals: 2 },
  {
    symbol: 'PM',
    name: 'Philip Morris International Inc.',
    klass: 'stock',
    decimals: 2,
  },
  {
    symbol: 'VZ',
    name: 'Verizon Communications Inc.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'PFE', name: 'Pfizer Inc.', klass: 'stock', decimals: 2 },
  {
    symbol: 'IBM',
    name: 'International Business Machines Corp.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'QCOM', name: 'Qualcomm Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'NEE', name: 'NextEra Energy Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'UNP', name: 'Union Pacific Corp.', klass: 'stock', decimals: 2 },
  {
    symbol: 'TXN',
    name: 'Texas Instruments Inc.',
    klass: 'stock',
    decimals: 2,
  },
  {
    symbol: 'BMY',
    name: 'Bristol-Myers Squibb Co.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'CMCSA', name: 'Comcast Corp.', klass: 'stock', decimals: 2 },
  { symbol: 'AMGN', name: 'Amgen Inc.', klass: 'stock', decimals: 2 },
  {
    symbol: 'UPS',
    name: 'United Parcel Service Inc.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'GE', name: 'General Electric Co.', klass: 'stock', decimals: 2 },
  {
    symbol: 'LOW',
    name: "Lowe's Companies Inc.",
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'CAT', name: 'Caterpillar Inc.', klass: 'stock', decimals: 2 },
  {
    symbol: 'AMAT',
    name: 'Applied Materials Inc.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'BA', name: 'Boeing Co.', klass: 'stock', decimals: 2 },
  {
    symbol: 'HON',
    name: 'Honeywell International Inc.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'RTX', name: 'RTX Corp.', klass: 'stock', decimals: 2 },
  {
    symbol: 'UBER',
    name: 'Uber Technologies Inc.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'SPGI', name: 'S&P Global Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'COP', name: 'ConocoPhillips', klass: 'stock', decimals: 2 },
  { symbol: 'MS', name: 'Morgan Stanley', klass: 'stock', decimals: 2 },
  { symbol: 'PLD', name: 'Prologis Inc.', klass: 'stock', decimals: 2 },
  {
    symbol: 'GS',
    name: 'Goldman Sachs Group Inc.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'CVS', name: 'CVS Health Corp.', klass: 'stock', decimals: 2 },
  { symbol: 'DE', name: 'Deere & Co.', klass: 'stock', decimals: 2 },
  {
    symbol: 'ISRG',
    name: 'Intuitive Surgical Inc.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'T', name: 'AT&T Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'SYK', name: 'Stryker Corp.', klass: 'stock', decimals: 2 },
  { symbol: 'BLK', name: 'BlackRock Inc.', klass: 'stock', decimals: 2 },
  {
    symbol: 'ELV',
    name: 'Elevance Health Inc.',
    klass: 'stock',
    decimals: 2,
  },
  {
    symbol: 'GILD',
    name: 'Gilead Sciences Inc.',
    klass: 'stock',
    decimals: 2,
  },
  {
    symbol: 'LMT',
    name: 'Lockheed Martin Corp.',
    klass: 'stock',
    decimals: 2,
  },
  {
    symbol: 'BKNG',
    name: 'Booking Holdings Inc.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'MDT', name: 'Medtronic plc', klass: 'stock', decimals: 2 },
  { symbol: 'TJX', name: 'TJX Companies Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'ADI', name: 'Analog Devices Inc.', klass: 'stock', decimals: 2 },
  {
    symbol: 'MMC',
    name: 'Marsh & McLennan Companies',
    klass: 'stock',
    decimals: 2,
  },
  {
    symbol: 'VRTX',
    name: 'Vertex Pharmaceuticals Inc.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'C', name: 'Citigroup Inc.', klass: 'stock', decimals: 2 },
  {
    symbol: 'ADP',
    name: 'Automatic Data Processing Inc.',
    klass: 'stock',
    decimals: 2,
  },
  {
    symbol: 'SCHW',
    name: 'Charles Schwab Corp.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'ZTS', name: 'Zoetis Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'CB', name: 'Chubb Ltd.', klass: 'stock', decimals: 2 },
  {
    symbol: 'REGN',
    name: 'Regeneron Pharmaceuticals Inc.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'CI', name: 'The Cigna Group', klass: 'stock', decimals: 2 },
  { symbol: 'MO', name: 'Altria Group Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'SO', name: 'Southern Co.', klass: 'stock', decimals: 2 },
  {
    symbol: 'BSX',
    name: 'Boston Scientific Corp.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'EOG', name: 'EOG Resources Inc.', klass: 'stock', decimals: 2 },
  { symbol: 'KLAC', name: 'KLA Corp.', klass: 'stock', decimals: 2 },
  {
    symbol: 'PANW',
    name: 'Palo Alto Networks Inc.',
    klass: 'stock',
    decimals: 2,
  },
  { symbol: 'FI', name: 'Fiserv Inc.', klass: 'stock', decimals: 2 },
  {
    symbol: 'MU',
    name: 'Micron Technology Inc.',
    klass: 'stock',
    decimals: 2,
  },
  {
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF Trust',
    klass: 'etf',
    decimals: 2,
  },
];
