// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v5.29.3
// source: common/order.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "common";

export enum OrderSide {
  ORDER_SIDE_UNSPECIFIED = 0,
  ORDER_SIDE_BUY = 1,
  ORDER_SIDE_SELL = 2,
  UNRECOGNIZED = -1,
}

export function orderSideFromJSON(object: any): OrderSide {
  switch (object) {
    case 0:
    case "ORDER_SIDE_UNSPECIFIED":
      return OrderSide.ORDER_SIDE_UNSPECIFIED;
    case 1:
    case "ORDER_SIDE_BUY":
      return OrderSide.ORDER_SIDE_BUY;
    case 2:
    case "ORDER_SIDE_SELL":
      return OrderSide.ORDER_SIDE_SELL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OrderSide.UNRECOGNIZED;
  }
}

export function orderSideToJSON(object: OrderSide): string {
  switch (object) {
    case OrderSide.ORDER_SIDE_UNSPECIFIED:
      return "ORDER_SIDE_UNSPECIFIED";
    case OrderSide.ORDER_SIDE_BUY:
      return "ORDER_SIDE_BUY";
    case OrderSide.ORDER_SIDE_SELL:
      return "ORDER_SIDE_SELL";
    case OrderSide.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OrderType {
  ORDER_TYPE_UNSPECIFIED = 0,
  ORDER_TYPE_LIMIT = 1,
  ORDER_TYPE_MARKET = 2,
  UNRECOGNIZED = -1,
}

export function orderTypeFromJSON(object: any): OrderType {
  switch (object) {
    case 0:
    case "ORDER_TYPE_UNSPECIFIED":
      return OrderType.ORDER_TYPE_UNSPECIFIED;
    case 1:
    case "ORDER_TYPE_LIMIT":
      return OrderType.ORDER_TYPE_LIMIT;
    case 2:
    case "ORDER_TYPE_MARKET":
      return OrderType.ORDER_TYPE_MARKET;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OrderType.UNRECOGNIZED;
  }
}

export function orderTypeToJSON(object: OrderType): string {
  switch (object) {
    case OrderType.ORDER_TYPE_UNSPECIFIED:
      return "ORDER_TYPE_UNSPECIFIED";
    case OrderType.ORDER_TYPE_LIMIT:
      return "ORDER_TYPE_LIMIT";
    case OrderType.ORDER_TYPE_MARKET:
      return "ORDER_TYPE_MARKET";
    case OrderType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum OrderStatus {
  ORDER_STATUS_UNSPECIFIED = 0,
  ORDER_STATUS_OPEN = 1,
  ORDER_STATUS_PARTIALLY_FILLED = 2,
  ORDER_STATUS_FILLED = 3,
  ORDER_STATUS_CANCELLED = 4,
  ORDER_STATUS_REJECTED = 5,
  UNRECOGNIZED = -1,
}

export function orderStatusFromJSON(object: any): OrderStatus {
  switch (object) {
    case 0:
    case "ORDER_STATUS_UNSPECIFIED":
      return OrderStatus.ORDER_STATUS_UNSPECIFIED;
    case 1:
    case "ORDER_STATUS_OPEN":
      return OrderStatus.ORDER_STATUS_OPEN;
    case 2:
    case "ORDER_STATUS_PARTIALLY_FILLED":
      return OrderStatus.ORDER_STATUS_PARTIALLY_FILLED;
    case 3:
    case "ORDER_STATUS_FILLED":
      return OrderStatus.ORDER_STATUS_FILLED;
    case 4:
    case "ORDER_STATUS_CANCELLED":
      return OrderStatus.ORDER_STATUS_CANCELLED;
    case 5:
    case "ORDER_STATUS_REJECTED":
      return OrderStatus.ORDER_STATUS_REJECTED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OrderStatus.UNRECOGNIZED;
  }
}

export function orderStatusToJSON(object: OrderStatus): string {
  switch (object) {
    case OrderStatus.ORDER_STATUS_UNSPECIFIED:
      return "ORDER_STATUS_UNSPECIFIED";
    case OrderStatus.ORDER_STATUS_OPEN:
      return "ORDER_STATUS_OPEN";
    case OrderStatus.ORDER_STATUS_PARTIALLY_FILLED:
      return "ORDER_STATUS_PARTIALLY_FILLED";
    case OrderStatus.ORDER_STATUS_FILLED:
      return "ORDER_STATUS_FILLED";
    case OrderStatus.ORDER_STATUS_CANCELLED:
      return "ORDER_STATUS_CANCELLED";
    case OrderStatus.ORDER_STATUS_REJECTED:
      return "ORDER_STATUS_REJECTED";
    case OrderStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum TimeInForce {
  TIME_IN_FORCE_UNSPECIFIED = 0,
  /** TIME_IN_FORCE_GTC - Good Till Cancelled */
  TIME_IN_FORCE_GTC = 1,
  /** TIME_IN_FORCE_IOC - Immediate or Cancel */
  TIME_IN_FORCE_IOC = 2,
  /** TIME_IN_FORCE_FOK - Fill or Kill */
  TIME_IN_FORCE_FOK = 3,
  UNRECOGNIZED = -1,
}

export function timeInForceFromJSON(object: any): TimeInForce {
  switch (object) {
    case 0:
    case "TIME_IN_FORCE_UNSPECIFIED":
      return TimeInForce.TIME_IN_FORCE_UNSPECIFIED;
    case 1:
    case "TIME_IN_FORCE_GTC":
      return TimeInForce.TIME_IN_FORCE_GTC;
    case 2:
    case "TIME_IN_FORCE_IOC":
      return TimeInForce.TIME_IN_FORCE_IOC;
    case 3:
    case "TIME_IN_FORCE_FOK":
      return TimeInForce.TIME_IN_FORCE_FOK;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TimeInForce.UNRECOGNIZED;
  }
}

export function timeInForceToJSON(object: TimeInForce): string {
  switch (object) {
    case TimeInForce.TIME_IN_FORCE_UNSPECIFIED:
      return "TIME_IN_FORCE_UNSPECIFIED";
    case TimeInForce.TIME_IN_FORCE_GTC:
      return "TIME_IN_FORCE_GTC";
    case TimeInForce.TIME_IN_FORCE_IOC:
      return "TIME_IN_FORCE_IOC";
    case TimeInForce.TIME_IN_FORCE_FOK:
      return "TIME_IN_FORCE_FOK";
    case TimeInForce.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Order {
  id?: string | undefined;
  tenantId?: string | undefined;
  side?: OrderSide | undefined;
  type?:
    | OrderType
    | undefined;
  /**
   * Using string for decimals to avoid precision loss (e.g. "0.00000001")
   * In Go/Node, these should be parsed with a Decimal library.
   */
  price?: string | undefined;
  quantity?: string | undefined;
  quantityFilled?: string | undefined;
  status?: OrderStatus | undefined;
  timeInForce?: TimeInForce | undefined;
  accountId?: string | undefined;
  instrumentId?:
    | string
    | undefined;
  /** JSON string for extra metadata */
  meta?:
    | string
    | undefined;
  /** Audit timestamps */
  createdAt?:
    | string
    | undefined;
  /** Unix timestamp */
  updatedAt?: string | undefined;
}

function createBaseOrder(): Order {
  return {
    id: "",
    tenantId: "",
    side: 0,
    type: 0,
    price: "",
    quantity: "",
    quantityFilled: "",
    status: 0,
    timeInForce: 0,
    accountId: "",
    instrumentId: "",
    meta: "",
    createdAt: "0",
    updatedAt: "0",
  };
}

export const Order: MessageFns<Order> = {
  encode(message: Order, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    if (message.side !== undefined && message.side !== 0) {
      writer.uint32(24).int32(message.side);
    }
    if (message.type !== undefined && message.type !== 0) {
      writer.uint32(32).int32(message.type);
    }
    if (message.price !== undefined && message.price !== "") {
      writer.uint32(42).string(message.price);
    }
    if (message.quantity !== undefined && message.quantity !== "") {
      writer.uint32(50).string(message.quantity);
    }
    if (message.quantityFilled !== undefined && message.quantityFilled !== "") {
      writer.uint32(58).string(message.quantityFilled);
    }
    if (message.status !== undefined && message.status !== 0) {
      writer.uint32(64).int32(message.status);
    }
    if (message.timeInForce !== undefined && message.timeInForce !== 0) {
      writer.uint32(72).int32(message.timeInForce);
    }
    if (message.accountId !== undefined && message.accountId !== "") {
      writer.uint32(82).string(message.accountId);
    }
    if (message.instrumentId !== undefined && message.instrumentId !== "") {
      writer.uint32(90).string(message.instrumentId);
    }
    if (message.meta !== undefined && message.meta !== "") {
      writer.uint32(98).string(message.meta);
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      writer.uint32(104).int64(message.createdAt);
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      writer.uint32(112).int64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Order {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrder();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.side = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.price = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.quantity = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.quantityFilled = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.timeInForce = reader.int32() as any;
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.accountId = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.instrumentId = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.meta = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.updatedAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Order {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      side: isSet(object.side) ? orderSideFromJSON(object.side) : 0,
      type: isSet(object.type) ? orderTypeFromJSON(object.type) : 0,
      price: isSet(object.price) ? globalThis.String(object.price) : "",
      quantity: isSet(object.quantity) ? globalThis.String(object.quantity) : "",
      quantityFilled: isSet(object.quantityFilled)
        ? globalThis.String(object.quantityFilled)
        : isSet(object.quantity_filled)
        ? globalThis.String(object.quantity_filled)
        : "",
      status: isSet(object.status) ? orderStatusFromJSON(object.status) : 0,
      timeInForce: isSet(object.timeInForce)
        ? timeInForceFromJSON(object.timeInForce)
        : isSet(object.time_in_force)
        ? timeInForceFromJSON(object.time_in_force)
        : 0,
      accountId: isSet(object.accountId)
        ? globalThis.String(object.accountId)
        : isSet(object.account_id)
        ? globalThis.String(object.account_id)
        : "",
      instrumentId: isSet(object.instrumentId)
        ? globalThis.String(object.instrumentId)
        : isSet(object.instrument_id)
        ? globalThis.String(object.instrument_id)
        : "",
      meta: isSet(object.meta) ? globalThis.String(object.meta) : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "0",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "0",
    };
  },

  toJSON(message: Order): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.side !== undefined && message.side !== 0) {
      obj.side = orderSideToJSON(message.side);
    }
    if (message.type !== undefined && message.type !== 0) {
      obj.type = orderTypeToJSON(message.type);
    }
    if (message.price !== undefined && message.price !== "") {
      obj.price = message.price;
    }
    if (message.quantity !== undefined && message.quantity !== "") {
      obj.quantity = message.quantity;
    }
    if (message.quantityFilled !== undefined && message.quantityFilled !== "") {
      obj.quantityFilled = message.quantityFilled;
    }
    if (message.status !== undefined && message.status !== 0) {
      obj.status = orderStatusToJSON(message.status);
    }
    if (message.timeInForce !== undefined && message.timeInForce !== 0) {
      obj.timeInForce = timeInForceToJSON(message.timeInForce);
    }
    if (message.accountId !== undefined && message.accountId !== "") {
      obj.accountId = message.accountId;
    }
    if (message.instrumentId !== undefined && message.instrumentId !== "") {
      obj.instrumentId = message.instrumentId;
    }
    if (message.meta !== undefined && message.meta !== "") {
      obj.meta = message.meta;
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Order>, I>>(base?: I): Order {
    return Order.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Order>, I>>(object: I): Order {
    const message = createBaseOrder();
    message.id = object.id ?? "";
    message.tenantId = object.tenantId ?? "";
    message.side = object.side ?? 0;
    message.type = object.type ?? 0;
    message.price = object.price ?? "";
    message.quantity = object.quantity ?? "";
    message.quantityFilled = object.quantityFilled ?? "";
    message.status = object.status ?? 0;
    message.timeInForce = object.timeInForce ?? 0;
    message.accountId = object.accountId ?? "";
    message.instrumentId = object.instrumentId ?? "";
    message.meta = object.meta ?? "";
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
