// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.29.3
// source: common/balance_snapshot.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BalanceSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId   string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AccountId  string `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	WalletId   string `protobuf:"bytes,4,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	AssetId    string `protobuf:"bytes,5,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Available  string `protobuf:"bytes,6,opt,name=available,proto3" json:"available,omitempty"`
	Locked     string `protobuf:"bytes,7,opt,name=locked,proto3" json:"locked,omitempty"`
	Total      string `protobuf:"bytes,8,opt,name=total,proto3" json:"total,omitempty"`
	SnapshotAt int64  `protobuf:"varint,9,opt,name=snapshot_at,json=snapshotAt,proto3" json:"snapshot_at,omitempty"`
	Meta       string `protobuf:"bytes,10,opt,name=meta,proto3" json:"meta,omitempty"` // JSON string
	CreatedAt  int64  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  int64  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *BalanceSnapshot) Reset() {
	*x = BalanceSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_balance_snapshot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceSnapshot) ProtoMessage() {}

func (x *BalanceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_common_balance_snapshot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceSnapshot.ProtoReflect.Descriptor instead.
func (*BalanceSnapshot) Descriptor() ([]byte, []int) {
	return file_common_balance_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BalanceSnapshot) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BalanceSnapshot) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BalanceSnapshot) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *BalanceSnapshot) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *BalanceSnapshot) GetAvailable() string {
	if x != nil {
		return x.Available
	}
	return ""
}

func (x *BalanceSnapshot) GetLocked() string {
	if x != nil {
		return x.Locked
	}
	return ""
}

func (x *BalanceSnapshot) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *BalanceSnapshot) GetSnapshotAt() int64 {
	if x != nil {
		return x.SnapshotAt
	}
	return 0
}

func (x *BalanceSnapshot) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *BalanceSnapshot) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *BalanceSnapshot) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_common_balance_snapshot_proto protoreflect.FileDescriptor

var file_common_balance_snapshot_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x5f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0xd4, 0x02, 0x0a, 0x0f, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c,
	0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x37,
	0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65,
	0x6e, 0x2d, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_balance_snapshot_proto_rawDescOnce sync.Once
	file_common_balance_snapshot_proto_rawDescData = file_common_balance_snapshot_proto_rawDesc
)

func file_common_balance_snapshot_proto_rawDescGZIP() []byte {
	file_common_balance_snapshot_proto_rawDescOnce.Do(func() {
		file_common_balance_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_balance_snapshot_proto_rawDescData)
	})
	return file_common_balance_snapshot_proto_rawDescData
}

var file_common_balance_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_balance_snapshot_proto_goTypes = []interface{}{
	(*BalanceSnapshot)(nil), // 0: common.BalanceSnapshot
}
var file_common_balance_snapshot_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_balance_snapshot_proto_init() }
func file_common_balance_snapshot_proto_init() {
	if File_common_balance_snapshot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_balance_snapshot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_balance_snapshot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_balance_snapshot_proto_goTypes,
		DependencyIndexes: file_common_balance_snapshot_proto_depIdxs,
		MessageInfos:      file_common_balance_snapshot_proto_msgTypes,
	}.Build()
	File_common_balance_snapshot_proto = out.File
	file_common_balance_snapshot_proto_rawDesc = nil
	file_common_balance_snapshot_proto_goTypes = nil
	file_common_balance_snapshot_proto_depIdxs = nil
}
