FROM golang:1.24-alpine

WORKDIR /app

# Install dependencies and air for hot reload
# Using Goproxy to avoid timeouts and checksum issues
ENV GOPROXY=https://proxy.golang.org,direct
ENV GOSUMDB=off

RUN apk add --no-cache protobuf-dev curl && \
    curl -sSfL https://raw.githubusercontent.com/air-verse/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Expose port
EXPOSE 50051 8080

# Run air for hot reload
CMD ["air", "-c", ".air.toml"]
