// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v5.29.3
// source: common/api_key.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "common";

export interface ApiKey {
  id?: string | undefined;
  tenantId?: string | undefined;
  name?: string | undefined;
  keyPrefix?: string | undefined;
  scopes?: string[] | undefined;
  expiresAt?: string | undefined;
  disabledAt?: string | undefined;
  membershipId?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
}

function createBaseApiKey(): ApiKey {
  return {
    id: "",
    tenantId: "",
    name: "",
    keyPrefix: "",
    scopes: [],
    expiresAt: "0",
    disabledAt: "0",
    membershipId: "",
    createdAt: "0",
    updatedAt: "0",
  };
}

export const ApiKey: MessageFns<ApiKey> = {
  encode(message: ApiKey, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    if (message.name !== undefined && message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.keyPrefix !== undefined && message.keyPrefix !== "") {
      writer.uint32(34).string(message.keyPrefix);
    }
    if (message.scopes !== undefined && message.scopes.length !== 0) {
      for (const v of message.scopes) {
        writer.uint32(42).string(v!);
      }
    }
    if (message.expiresAt !== undefined && message.expiresAt !== "0") {
      writer.uint32(48).int64(message.expiresAt);
    }
    if (message.disabledAt !== undefined && message.disabledAt !== "0") {
      writer.uint32(56).int64(message.disabledAt);
    }
    if (message.membershipId !== undefined && message.membershipId !== "") {
      writer.uint32(66).string(message.membershipId);
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      writer.uint32(72).int64(message.createdAt);
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      writer.uint32(80).int64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApiKey {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApiKey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.keyPrefix = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const el = reader.string();
          if (el !== undefined) {
            message.scopes!.push(el);
          }
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.expiresAt = reader.int64().toString();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.disabledAt = reader.int64().toString();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.membershipId = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.updatedAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApiKey {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      keyPrefix: isSet(object.keyPrefix)
        ? globalThis.String(object.keyPrefix)
        : isSet(object.key_prefix)
        ? globalThis.String(object.key_prefix)
        : "",
      scopes: globalThis.Array.isArray(object?.scopes)
        ? object.scopes.map((e: any) => globalThis.String(e))
        : [],
      expiresAt: isSet(object.expiresAt)
        ? globalThis.String(object.expiresAt)
        : isSet(object.expires_at)
        ? globalThis.String(object.expires_at)
        : "0",
      disabledAt: isSet(object.disabledAt)
        ? globalThis.String(object.disabledAt)
        : isSet(object.disabled_at)
        ? globalThis.String(object.disabled_at)
        : "0",
      membershipId: isSet(object.membershipId)
        ? globalThis.String(object.membershipId)
        : isSet(object.membership_id)
        ? globalThis.String(object.membership_id)
        : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "0",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "0",
    };
  },

  toJSON(message: ApiKey): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.name !== undefined && message.name !== "") {
      obj.name = message.name;
    }
    if (message.keyPrefix !== undefined && message.keyPrefix !== "") {
      obj.keyPrefix = message.keyPrefix;
    }
    if (message.scopes?.length) {
      obj.scopes = message.scopes;
    }
    if (message.expiresAt !== undefined && message.expiresAt !== "0") {
      obj.expiresAt = message.expiresAt;
    }
    if (message.disabledAt !== undefined && message.disabledAt !== "0") {
      obj.disabledAt = message.disabledAt;
    }
    if (message.membershipId !== undefined && message.membershipId !== "") {
      obj.membershipId = message.membershipId;
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApiKey>, I>>(base?: I): ApiKey {
    return ApiKey.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApiKey>, I>>(object: I): ApiKey {
    const message = createBaseApiKey();
    message.id = object.id ?? "";
    message.tenantId = object.tenantId ?? "";
    message.name = object.name ?? "";
    message.keyPrefix = object.keyPrefix ?? "";
    message.scopes = object.scopes?.map((e) => e) || [];
    message.expiresAt = object.expiresAt ?? "0";
    message.disabledAt = object.disabledAt ?? "0";
    message.membershipId = object.membershipId ?? "";
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
