// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v5.29.3
// source: common/balance_snapshot.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "common";

export interface BalanceSnapshot {
  id?: string | undefined;
  tenantId?: string | undefined;
  accountId?: string | undefined;
  walletId?: string | undefined;
  assetId?:
    | string
    | undefined;
  /** Decimal(72,0) */
  available?:
    | string
    | undefined;
  /** Decimal(72,0) */
  locked?:
    | string
    | undefined;
  /** Decimal(72,0) */
  total?: string | undefined;
  snapshotAt?:
    | string
    | undefined;
  /** JSON string */
  meta?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
}

function createBaseBalanceSnapshot(): BalanceSnapshot {
  return {
    id: "",
    tenantId: "",
    accountId: "",
    walletId: "",
    assetId: "",
    available: "",
    locked: "",
    total: "",
    snapshotAt: "0",
    meta: "",
    createdAt: "0",
    updatedAt: "0",
  };
}

export const BalanceSnapshot: MessageFns<BalanceSnapshot> = {
  encode(message: BalanceSnapshot, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    if (message.accountId !== undefined && message.accountId !== "") {
      writer.uint32(26).string(message.accountId);
    }
    if (message.walletId !== undefined && message.walletId !== "") {
      writer.uint32(34).string(message.walletId);
    }
    if (message.assetId !== undefined && message.assetId !== "") {
      writer.uint32(42).string(message.assetId);
    }
    if (message.available !== undefined && message.available !== "") {
      writer.uint32(50).string(message.available);
    }
    if (message.locked !== undefined && message.locked !== "") {
      writer.uint32(58).string(message.locked);
    }
    if (message.total !== undefined && message.total !== "") {
      writer.uint32(66).string(message.total);
    }
    if (message.snapshotAt !== undefined && message.snapshotAt !== "0") {
      writer.uint32(72).int64(message.snapshotAt);
    }
    if (message.meta !== undefined && message.meta !== "") {
      writer.uint32(82).string(message.meta);
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      writer.uint32(88).int64(message.createdAt);
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      writer.uint32(96).int64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BalanceSnapshot {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBalanceSnapshot();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.accountId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.walletId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.assetId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.available = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.locked = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.total = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.snapshotAt = reader.int64().toString();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.meta = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.updatedAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BalanceSnapshot {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      accountId: isSet(object.accountId)
        ? globalThis.String(object.accountId)
        : isSet(object.account_id)
        ? globalThis.String(object.account_id)
        : "",
      walletId: isSet(object.walletId)
        ? globalThis.String(object.walletId)
        : isSet(object.wallet_id)
        ? globalThis.String(object.wallet_id)
        : "",
      assetId: isSet(object.assetId)
        ? globalThis.String(object.assetId)
        : isSet(object.asset_id)
        ? globalThis.String(object.asset_id)
        : "",
      available: isSet(object.available) ? globalThis.String(object.available) : "",
      locked: isSet(object.locked) ? globalThis.String(object.locked) : "",
      total: isSet(object.total) ? globalThis.String(object.total) : "",
      snapshotAt: isSet(object.snapshotAt)
        ? globalThis.String(object.snapshotAt)
        : isSet(object.snapshot_at)
        ? globalThis.String(object.snapshot_at)
        : "0",
      meta: isSet(object.meta) ? globalThis.String(object.meta) : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "0",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "0",
    };
  },

  toJSON(message: BalanceSnapshot): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.accountId !== undefined && message.accountId !== "") {
      obj.accountId = message.accountId;
    }
    if (message.walletId !== undefined && message.walletId !== "") {
      obj.walletId = message.walletId;
    }
    if (message.assetId !== undefined && message.assetId !== "") {
      obj.assetId = message.assetId;
    }
    if (message.available !== undefined && message.available !== "") {
      obj.available = message.available;
    }
    if (message.locked !== undefined && message.locked !== "") {
      obj.locked = message.locked;
    }
    if (message.total !== undefined && message.total !== "") {
      obj.total = message.total;
    }
    if (message.snapshotAt !== undefined && message.snapshotAt !== "0") {
      obj.snapshotAt = message.snapshotAt;
    }
    if (message.meta !== undefined && message.meta !== "") {
      obj.meta = message.meta;
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BalanceSnapshot>, I>>(base?: I): BalanceSnapshot {
    return BalanceSnapshot.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BalanceSnapshot>, I>>(object: I): BalanceSnapshot {
    const message = createBaseBalanceSnapshot();
    message.id = object.id ?? "";
    message.tenantId = object.tenantId ?? "";
    message.accountId = object.accountId ?? "";
    message.walletId = object.walletId ?? "";
    message.assetId = object.assetId ?? "";
    message.available = object.available ?? "";
    message.locked = object.locked ?? "";
    message.total = object.total ?? "";
    message.snapshotAt = object.snapshotAt ?? "0";
    message.meta = object.meta ?? "";
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
