// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v5.29.3
// source: common/deposit.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "common";

export interface Deposit {
  id?: string | undefined;
  tenantId?: string | undefined;
  accountId?: string | undefined;
  assetId?:
    | string
    | undefined;
  /** Added for context, though schema links via account/asset */
  walletId?:
    | string
    | undefined;
  /** Decimal(72,0) */
  amount?: string | undefined;
  status?: string | undefined;
  chain?: string | undefined;
  txHash?: string | undefined;
  fromAddress?: string | undefined;
  confirmations?: number | undefined;
  requiredConfirmations?: number | undefined;
  detectedAt?: string | undefined;
  confirmedAt?: string | undefined;
  creditedAt?:
    | string
    | undefined;
  /** JSON string */
  meta?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
}

function createBaseDeposit(): Deposit {
  return {
    id: "",
    tenantId: "",
    accountId: "",
    assetId: "",
    walletId: "",
    amount: "",
    status: "",
    chain: "",
    txHash: "",
    fromAddress: "",
    confirmations: 0,
    requiredConfirmations: 0,
    detectedAt: "0",
    confirmedAt: "0",
    creditedAt: "0",
    meta: "",
    createdAt: "0",
    updatedAt: "0",
  };
}

export const Deposit: MessageFns<Deposit> = {
  encode(message: Deposit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    if (message.accountId !== undefined && message.accountId !== "") {
      writer.uint32(26).string(message.accountId);
    }
    if (message.assetId !== undefined && message.assetId !== "") {
      writer.uint32(34).string(message.assetId);
    }
    if (message.walletId !== undefined && message.walletId !== "") {
      writer.uint32(42).string(message.walletId);
    }
    if (message.amount !== undefined && message.amount !== "") {
      writer.uint32(50).string(message.amount);
    }
    if (message.status !== undefined && message.status !== "") {
      writer.uint32(58).string(message.status);
    }
    if (message.chain !== undefined && message.chain !== "") {
      writer.uint32(66).string(message.chain);
    }
    if (message.txHash !== undefined && message.txHash !== "") {
      writer.uint32(74).string(message.txHash);
    }
    if (message.fromAddress !== undefined && message.fromAddress !== "") {
      writer.uint32(82).string(message.fromAddress);
    }
    if (message.confirmations !== undefined && message.confirmations !== 0) {
      writer.uint32(88).int32(message.confirmations);
    }
    if (message.requiredConfirmations !== undefined && message.requiredConfirmations !== 0) {
      writer.uint32(96).int32(message.requiredConfirmations);
    }
    if (message.detectedAt !== undefined && message.detectedAt !== "0") {
      writer.uint32(104).int64(message.detectedAt);
    }
    if (message.confirmedAt !== undefined && message.confirmedAt !== "0") {
      writer.uint32(112).int64(message.confirmedAt);
    }
    if (message.creditedAt !== undefined && message.creditedAt !== "0") {
      writer.uint32(120).int64(message.creditedAt);
    }
    if (message.meta !== undefined && message.meta !== "") {
      writer.uint32(130).string(message.meta);
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      writer.uint32(136).int64(message.createdAt);
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      writer.uint32(144).int64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Deposit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeposit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.accountId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.assetId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.walletId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.chain = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.txHash = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.fromAddress = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.confirmations = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.requiredConfirmations = reader.int32();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.detectedAt = reader.int64().toString();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.confirmedAt = reader.int64().toString();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.creditedAt = reader.int64().toString();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.meta = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.updatedAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Deposit {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      accountId: isSet(object.accountId)
        ? globalThis.String(object.accountId)
        : isSet(object.account_id)
        ? globalThis.String(object.account_id)
        : "",
      assetId: isSet(object.assetId)
        ? globalThis.String(object.assetId)
        : isSet(object.asset_id)
        ? globalThis.String(object.asset_id)
        : "",
      walletId: isSet(object.walletId)
        ? globalThis.String(object.walletId)
        : isSet(object.wallet_id)
        ? globalThis.String(object.wallet_id)
        : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      chain: isSet(object.chain) ? globalThis.String(object.chain) : "",
      txHash: isSet(object.txHash)
        ? globalThis.String(object.txHash)
        : isSet(object.tx_hash)
        ? globalThis.String(object.tx_hash)
        : "",
      fromAddress: isSet(object.fromAddress)
        ? globalThis.String(object.fromAddress)
        : isSet(object.from_address)
        ? globalThis.String(object.from_address)
        : "",
      confirmations: isSet(object.confirmations) ? globalThis.Number(object.confirmations) : 0,
      requiredConfirmations: isSet(object.requiredConfirmations)
        ? globalThis.Number(object.requiredConfirmations)
        : isSet(object.required_confirmations)
        ? globalThis.Number(object.required_confirmations)
        : 0,
      detectedAt: isSet(object.detectedAt)
        ? globalThis.String(object.detectedAt)
        : isSet(object.detected_at)
        ? globalThis.String(object.detected_at)
        : "0",
      confirmedAt: isSet(object.confirmedAt)
        ? globalThis.String(object.confirmedAt)
        : isSet(object.confirmed_at)
        ? globalThis.String(object.confirmed_at)
        : "0",
      creditedAt: isSet(object.creditedAt)
        ? globalThis.String(object.creditedAt)
        : isSet(object.credited_at)
        ? globalThis.String(object.credited_at)
        : "0",
      meta: isSet(object.meta) ? globalThis.String(object.meta) : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "0",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "0",
    };
  },

  toJSON(message: Deposit): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.accountId !== undefined && message.accountId !== "") {
      obj.accountId = message.accountId;
    }
    if (message.assetId !== undefined && message.assetId !== "") {
      obj.assetId = message.assetId;
    }
    if (message.walletId !== undefined && message.walletId !== "") {
      obj.walletId = message.walletId;
    }
    if (message.amount !== undefined && message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.status !== undefined && message.status !== "") {
      obj.status = message.status;
    }
    if (message.chain !== undefined && message.chain !== "") {
      obj.chain = message.chain;
    }
    if (message.txHash !== undefined && message.txHash !== "") {
      obj.txHash = message.txHash;
    }
    if (message.fromAddress !== undefined && message.fromAddress !== "") {
      obj.fromAddress = message.fromAddress;
    }
    if (message.confirmations !== undefined && message.confirmations !== 0) {
      obj.confirmations = Math.round(message.confirmations);
    }
    if (message.requiredConfirmations !== undefined && message.requiredConfirmations !== 0) {
      obj.requiredConfirmations = Math.round(message.requiredConfirmations);
    }
    if (message.detectedAt !== undefined && message.detectedAt !== "0") {
      obj.detectedAt = message.detectedAt;
    }
    if (message.confirmedAt !== undefined && message.confirmedAt !== "0") {
      obj.confirmedAt = message.confirmedAt;
    }
    if (message.creditedAt !== undefined && message.creditedAt !== "0") {
      obj.creditedAt = message.creditedAt;
    }
    if (message.meta !== undefined && message.meta !== "") {
      obj.meta = message.meta;
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Deposit>, I>>(base?: I): Deposit {
    return Deposit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Deposit>, I>>(object: I): Deposit {
    const message = createBaseDeposit();
    message.id = object.id ?? "";
    message.tenantId = object.tenantId ?? "";
    message.accountId = object.accountId ?? "";
    message.assetId = object.assetId ?? "";
    message.walletId = object.walletId ?? "";
    message.amount = object.amount ?? "";
    message.status = object.status ?? "";
    message.chain = object.chain ?? "";
    message.txHash = object.txHash ?? "";
    message.fromAddress = object.fromAddress ?? "";
    message.confirmations = object.confirmations ?? 0;
    message.requiredConfirmations = object.requiredConfirmations ?? 0;
    message.detectedAt = object.detectedAt ?? "0";
    message.confirmedAt = object.confirmedAt ?? "0";
    message.creditedAt = object.creditedAt ?? "0";
    message.meta = object.meta ?? "";
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
