// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v5.29.3
// source: common/fee_schedule.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "common";

export interface FeeSchedule {
  id?: string | undefined;
  tenantId?:
    | string
    | undefined;
  /** e.g. "global", "user", "vip" */
  scope?: string | undefined;
  makerFeeBps?: number | undefined;
  takerFeeBps?:
    | number
    | undefined;
  /** string for precision if needed, Prisma said Int? but fees usually have decimals */
  minFeeAmount?: string | undefined;
  effectiveFrom?: string | undefined;
  effectiveTo?: string | undefined;
  tier?: string | undefined;
  accountId?: string | undefined;
  instrumentId?:
    | string
    | undefined;
  /** JSON string */
  meta?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
}

function createBaseFeeSchedule(): FeeSchedule {
  return {
    id: "",
    tenantId: "",
    scope: "",
    makerFeeBps: 0,
    takerFeeBps: 0,
    minFeeAmount: "",
    effectiveFrom: "0",
    effectiveTo: "0",
    tier: "",
    accountId: "",
    instrumentId: "",
    meta: "",
    createdAt: "0",
    updatedAt: "0",
  };
}

export const FeeSchedule: MessageFns<FeeSchedule> = {
  encode(message: FeeSchedule, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    if (message.scope !== undefined && message.scope !== "") {
      writer.uint32(26).string(message.scope);
    }
    if (message.makerFeeBps !== undefined && message.makerFeeBps !== 0) {
      writer.uint32(32).int32(message.makerFeeBps);
    }
    if (message.takerFeeBps !== undefined && message.takerFeeBps !== 0) {
      writer.uint32(40).int32(message.takerFeeBps);
    }
    if (message.minFeeAmount !== undefined && message.minFeeAmount !== "") {
      writer.uint32(50).string(message.minFeeAmount);
    }
    if (message.effectiveFrom !== undefined && message.effectiveFrom !== "0") {
      writer.uint32(56).int64(message.effectiveFrom);
    }
    if (message.effectiveTo !== undefined && message.effectiveTo !== "0") {
      writer.uint32(64).int64(message.effectiveTo);
    }
    if (message.tier !== undefined && message.tier !== "") {
      writer.uint32(74).string(message.tier);
    }
    if (message.accountId !== undefined && message.accountId !== "") {
      writer.uint32(82).string(message.accountId);
    }
    if (message.instrumentId !== undefined && message.instrumentId !== "") {
      writer.uint32(90).string(message.instrumentId);
    }
    if (message.meta !== undefined && message.meta !== "") {
      writer.uint32(98).string(message.meta);
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      writer.uint32(104).int64(message.createdAt);
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      writer.uint32(112).int64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FeeSchedule {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFeeSchedule();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.scope = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.makerFeeBps = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.takerFeeBps = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.minFeeAmount = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.effectiveFrom = reader.int64().toString();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.effectiveTo = reader.int64().toString();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.tier = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.accountId = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.instrumentId = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.meta = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.updatedAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FeeSchedule {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      scope: isSet(object.scope) ? globalThis.String(object.scope) : "",
      makerFeeBps: isSet(object.makerFeeBps)
        ? globalThis.Number(object.makerFeeBps)
        : isSet(object.maker_fee_bps)
        ? globalThis.Number(object.maker_fee_bps)
        : 0,
      takerFeeBps: isSet(object.takerFeeBps)
        ? globalThis.Number(object.takerFeeBps)
        : isSet(object.taker_fee_bps)
        ? globalThis.Number(object.taker_fee_bps)
        : 0,
      minFeeAmount: isSet(object.minFeeAmount)
        ? globalThis.String(object.minFeeAmount)
        : isSet(object.min_fee_amount)
        ? globalThis.String(object.min_fee_amount)
        : "",
      effectiveFrom: isSet(object.effectiveFrom)
        ? globalThis.String(object.effectiveFrom)
        : isSet(object.effective_from)
        ? globalThis.String(object.effective_from)
        : "0",
      effectiveTo: isSet(object.effectiveTo)
        ? globalThis.String(object.effectiveTo)
        : isSet(object.effective_to)
        ? globalThis.String(object.effective_to)
        : "0",
      tier: isSet(object.tier) ? globalThis.String(object.tier) : "",
      accountId: isSet(object.accountId)
        ? globalThis.String(object.accountId)
        : isSet(object.account_id)
        ? globalThis.String(object.account_id)
        : "",
      instrumentId: isSet(object.instrumentId)
        ? globalThis.String(object.instrumentId)
        : isSet(object.instrument_id)
        ? globalThis.String(object.instrument_id)
        : "",
      meta: isSet(object.meta) ? globalThis.String(object.meta) : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "0",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "0",
    };
  },

  toJSON(message: FeeSchedule): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.scope !== undefined && message.scope !== "") {
      obj.scope = message.scope;
    }
    if (message.makerFeeBps !== undefined && message.makerFeeBps !== 0) {
      obj.makerFeeBps = Math.round(message.makerFeeBps);
    }
    if (message.takerFeeBps !== undefined && message.takerFeeBps !== 0) {
      obj.takerFeeBps = Math.round(message.takerFeeBps);
    }
    if (message.minFeeAmount !== undefined && message.minFeeAmount !== "") {
      obj.minFeeAmount = message.minFeeAmount;
    }
    if (message.effectiveFrom !== undefined && message.effectiveFrom !== "0") {
      obj.effectiveFrom = message.effectiveFrom;
    }
    if (message.effectiveTo !== undefined && message.effectiveTo !== "0") {
      obj.effectiveTo = message.effectiveTo;
    }
    if (message.tier !== undefined && message.tier !== "") {
      obj.tier = message.tier;
    }
    if (message.accountId !== undefined && message.accountId !== "") {
      obj.accountId = message.accountId;
    }
    if (message.instrumentId !== undefined && message.instrumentId !== "") {
      obj.instrumentId = message.instrumentId;
    }
    if (message.meta !== undefined && message.meta !== "") {
      obj.meta = message.meta;
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FeeSchedule>, I>>(base?: I): FeeSchedule {
    return FeeSchedule.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FeeSchedule>, I>>(object: I): FeeSchedule {
    const message = createBaseFeeSchedule();
    message.id = object.id ?? "";
    message.tenantId = object.tenantId ?? "";
    message.scope = object.scope ?? "";
    message.makerFeeBps = object.makerFeeBps ?? 0;
    message.takerFeeBps = object.takerFeeBps ?? 0;
    message.minFeeAmount = object.minFeeAmount ?? "";
    message.effectiveFrom = object.effectiveFrom ?? "0";
    message.effectiveTo = object.effectiveTo ?? "0";
    message.tier = object.tier ?? "";
    message.accountId = object.accountId ?? "";
    message.instrumentId = object.instrumentId ?? "";
    message.meta = object.meta ?? "";
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
