// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v5.29.3
// source: common/fill.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "common";

export interface Fill {
  id?: string | undefined;
  tenantId?: string | undefined;
  tradeId?:
    | string
    | undefined;
  /** "buy" or "sell" */
  side?:
    | string
    | undefined;
  /** Decimal(72,0) */
  price?:
    | string
    | undefined;
  /** Decimal(72,0) */
  quantity?:
    | string
    | undefined;
  /** Decimal(72,0) */
  fee?:
    | string
    | undefined;
  /** JSON string */
  meta?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
}

function createBaseFill(): Fill {
  return {
    id: "",
    tenantId: "",
    tradeId: "",
    side: "",
    price: "",
    quantity: "",
    fee: "",
    meta: "",
    createdAt: "0",
    updatedAt: "0",
  };
}

export const Fill: MessageFns<Fill> = {
  encode(message: Fill, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    if (message.tradeId !== undefined && message.tradeId !== "") {
      writer.uint32(26).string(message.tradeId);
    }
    if (message.side !== undefined && message.side !== "") {
      writer.uint32(34).string(message.side);
    }
    if (message.price !== undefined && message.price !== "") {
      writer.uint32(42).string(message.price);
    }
    if (message.quantity !== undefined && message.quantity !== "") {
      writer.uint32(50).string(message.quantity);
    }
    if (message.fee !== undefined && message.fee !== "") {
      writer.uint32(58).string(message.fee);
    }
    if (message.meta !== undefined && message.meta !== "") {
      writer.uint32(66).string(message.meta);
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      writer.uint32(72).int64(message.createdAt);
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      writer.uint32(80).int64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Fill {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFill();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.tradeId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.side = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.price = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.quantity = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.fee = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.meta = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.updatedAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Fill {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      tradeId: isSet(object.tradeId)
        ? globalThis.String(object.tradeId)
        : isSet(object.trade_id)
        ? globalThis.String(object.trade_id)
        : "",
      side: isSet(object.side) ? globalThis.String(object.side) : "",
      price: isSet(object.price) ? globalThis.String(object.price) : "",
      quantity: isSet(object.quantity) ? globalThis.String(object.quantity) : "",
      fee: isSet(object.fee) ? globalThis.String(object.fee) : "",
      meta: isSet(object.meta) ? globalThis.String(object.meta) : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "0",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "0",
    };
  },

  toJSON(message: Fill): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.tradeId !== undefined && message.tradeId !== "") {
      obj.tradeId = message.tradeId;
    }
    if (message.side !== undefined && message.side !== "") {
      obj.side = message.side;
    }
    if (message.price !== undefined && message.price !== "") {
      obj.price = message.price;
    }
    if (message.quantity !== undefined && message.quantity !== "") {
      obj.quantity = message.quantity;
    }
    if (message.fee !== undefined && message.fee !== "") {
      obj.fee = message.fee;
    }
    if (message.meta !== undefined && message.meta !== "") {
      obj.meta = message.meta;
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Fill>, I>>(base?: I): Fill {
    return Fill.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Fill>, I>>(object: I): Fill {
    const message = createBaseFill();
    message.id = object.id ?? "";
    message.tenantId = object.tenantId ?? "";
    message.tradeId = object.tradeId ?? "";
    message.side = object.side ?? "";
    message.price = object.price ?? "";
    message.quantity = object.quantity ?? "";
    message.fee = object.fee ?? "";
    message.meta = object.meta ?? "";
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
