// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v5.29.3
// source: common/ledger_entry.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "common";

export interface LedgerEntry {
  id?: string | undefined;
  tenantId?: string | undefined;
  eventId?: string | undefined;
  accountId?:
    | string
    | undefined;
  /** Positive or negative */
  amount?:
    | string
    | undefined;
  /** JSON string */
  meta?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
}

function createBaseLedgerEntry(): LedgerEntry {
  return { id: "", tenantId: "", eventId: "", accountId: "", amount: "", meta: "", createdAt: "0", updatedAt: "0" };
}

export const LedgerEntry: MessageFns<LedgerEntry> = {
  encode(message: LedgerEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    if (message.eventId !== undefined && message.eventId !== "") {
      writer.uint32(26).string(message.eventId);
    }
    if (message.accountId !== undefined && message.accountId !== "") {
      writer.uint32(34).string(message.accountId);
    }
    if (message.amount !== undefined && message.amount !== "") {
      writer.uint32(42).string(message.amount);
    }
    if (message.meta !== undefined && message.meta !== "") {
      writer.uint32(50).string(message.meta);
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      writer.uint32(56).int64(message.createdAt);
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      writer.uint32(64).int64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LedgerEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLedgerEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.accountId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.meta = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.updatedAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LedgerEntry {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      eventId: isSet(object.eventId)
        ? globalThis.String(object.eventId)
        : isSet(object.event_id)
        ? globalThis.String(object.event_id)
        : "",
      accountId: isSet(object.accountId)
        ? globalThis.String(object.accountId)
        : isSet(object.account_id)
        ? globalThis.String(object.account_id)
        : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      meta: isSet(object.meta) ? globalThis.String(object.meta) : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "0",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "0",
    };
  },

  toJSON(message: LedgerEntry): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.eventId !== undefined && message.eventId !== "") {
      obj.eventId = message.eventId;
    }
    if (message.accountId !== undefined && message.accountId !== "") {
      obj.accountId = message.accountId;
    }
    if (message.amount !== undefined && message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.meta !== undefined && message.meta !== "") {
      obj.meta = message.meta;
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LedgerEntry>, I>>(base?: I): LedgerEntry {
    return LedgerEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LedgerEntry>, I>>(object: I): LedgerEntry {
    const message = createBaseLedgerEntry();
    message.id = object.id ?? "";
    message.tenantId = object.tenantId ?? "";
    message.eventId = object.eventId ?? "";
    message.accountId = object.accountId ?? "";
    message.amount = object.amount ?? "";
    message.meta = object.meta ?? "";
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
