// @ts-nocheck
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v5.29.3
// source: common/market_maker.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "common";

export interface MarketMaker {
  id?: string | undefined;
  tenantId?: string | undefined;
  organizationName?: string | undefined;
  contactEmail?: string | undefined;
  contactPhone?: string | undefined;
  status?: string | undefined;
  tier?: string | undefined;
  marketsSupported?: string | undefined;
  minQuoteSize?: number | undefined;
  maxQuoteSize?: number | undefined;
  spreadLimit?: number | undefined;
  quoteObligation?: boolean | undefined;
  dailyVolumeTarget?: number | undefined;
  makerFee?: number | undefined;
  takerFee?: number | undefined;
  rebateRate?: number | undefined;
  rebateBalance?: number | undefined;
  apiAccess?: boolean | undefined;
  maxOrdersPerSecond?: number | undefined;
  directMarketAccess?: boolean | undefined;
  contractSignedAt?: string | undefined;
  obligationViolationCount?:
    | number
    | undefined;
  /** JSON string */
  auditLog?: string | undefined;
  notesInternal?: string | undefined;
  specialOrderTypes?: string | undefined;
  minFeeAmount?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
}

function createBaseMarketMaker(): MarketMaker {
  return {
    id: "",
    tenantId: "",
    organizationName: "",
    contactEmail: "",
    contactPhone: "",
    status: "",
    tier: "",
    marketsSupported: "",
    minQuoteSize: 0,
    maxQuoteSize: 0,
    spreadLimit: 0,
    quoteObligation: false,
    dailyVolumeTarget: 0,
    makerFee: 0,
    takerFee: 0,
    rebateRate: 0,
    rebateBalance: 0,
    apiAccess: false,
    maxOrdersPerSecond: 0,
    directMarketAccess: false,
    contractSignedAt: "0",
    obligationViolationCount: 0,
    auditLog: "",
    notesInternal: "",
    specialOrderTypes: "",
    minFeeAmount: "",
    createdAt: "0",
    updatedAt: "0",
  };
}

export const MarketMaker: MessageFns<MarketMaker> = {
  encode(message: MarketMaker, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    if (message.organizationName !== undefined && message.organizationName !== "") {
      writer.uint32(26).string(message.organizationName);
    }
    if (message.contactEmail !== undefined && message.contactEmail !== "") {
      writer.uint32(34).string(message.contactEmail);
    }
    if (message.contactPhone !== undefined && message.contactPhone !== "") {
      writer.uint32(42).string(message.contactPhone);
    }
    if (message.status !== undefined && message.status !== "") {
      writer.uint32(50).string(message.status);
    }
    if (message.tier !== undefined && message.tier !== "") {
      writer.uint32(58).string(message.tier);
    }
    if (message.marketsSupported !== undefined && message.marketsSupported !== "") {
      writer.uint32(66).string(message.marketsSupported);
    }
    if (message.minQuoteSize !== undefined && message.minQuoteSize !== 0) {
      writer.uint32(72).int32(message.minQuoteSize);
    }
    if (message.maxQuoteSize !== undefined && message.maxQuoteSize !== 0) {
      writer.uint32(80).int32(message.maxQuoteSize);
    }
    if (message.spreadLimit !== undefined && message.spreadLimit !== 0) {
      writer.uint32(88).int32(message.spreadLimit);
    }
    if (message.quoteObligation !== undefined && message.quoteObligation !== false) {
      writer.uint32(96).bool(message.quoteObligation);
    }
    if (message.dailyVolumeTarget !== undefined && message.dailyVolumeTarget !== 0) {
      writer.uint32(104).int32(message.dailyVolumeTarget);
    }
    if (message.makerFee !== undefined && message.makerFee !== 0) {
      writer.uint32(112).int32(message.makerFee);
    }
    if (message.takerFee !== undefined && message.takerFee !== 0) {
      writer.uint32(120).int32(message.takerFee);
    }
    if (message.rebateRate !== undefined && message.rebateRate !== 0) {
      writer.uint32(128).int32(message.rebateRate);
    }
    if (message.rebateBalance !== undefined && message.rebateBalance !== 0) {
      writer.uint32(136).int32(message.rebateBalance);
    }
    if (message.apiAccess !== undefined && message.apiAccess !== false) {
      writer.uint32(144).bool(message.apiAccess);
    }
    if (message.maxOrdersPerSecond !== undefined && message.maxOrdersPerSecond !== 0) {
      writer.uint32(152).int32(message.maxOrdersPerSecond);
    }
    if (message.directMarketAccess !== undefined && message.directMarketAccess !== false) {
      writer.uint32(160).bool(message.directMarketAccess);
    }
    if (message.contractSignedAt !== undefined && message.contractSignedAt !== "0") {
      writer.uint32(168).int64(message.contractSignedAt);
    }
    if (message.obligationViolationCount !== undefined && message.obligationViolationCount !== 0) {
      writer.uint32(176).int32(message.obligationViolationCount);
    }
    if (message.auditLog !== undefined && message.auditLog !== "") {
      writer.uint32(186).string(message.auditLog);
    }
    if (message.notesInternal !== undefined && message.notesInternal !== "") {
      writer.uint32(194).string(message.notesInternal);
    }
    if (message.specialOrderTypes !== undefined && message.specialOrderTypes !== "") {
      writer.uint32(202).string(message.specialOrderTypes);
    }
    if (message.minFeeAmount !== undefined && message.minFeeAmount !== "") {
      writer.uint32(210).string(message.minFeeAmount);
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      writer.uint32(216).int64(message.createdAt);
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      writer.uint32(224).int64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarketMaker {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarketMaker();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.organizationName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.contactEmail = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.contactPhone = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.tier = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.marketsSupported = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.minQuoteSize = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.maxQuoteSize = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.spreadLimit = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.quoteObligation = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.dailyVolumeTarget = reader.int32();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.makerFee = reader.int32();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.takerFee = reader.int32();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.rebateRate = reader.int32();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.rebateBalance = reader.int32();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.apiAccess = reader.bool();
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.maxOrdersPerSecond = reader.int32();
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.directMarketAccess = reader.bool();
          continue;
        }
        case 21: {
          if (tag !== 168) {
            break;
          }

          message.contractSignedAt = reader.int64().toString();
          continue;
        }
        case 22: {
          if (tag !== 176) {
            break;
          }

          message.obligationViolationCount = reader.int32();
          continue;
        }
        case 23: {
          if (tag !== 186) {
            break;
          }

          message.auditLog = reader.string();
          continue;
        }
        case 24: {
          if (tag !== 194) {
            break;
          }

          message.notesInternal = reader.string();
          continue;
        }
        case 25: {
          if (tag !== 202) {
            break;
          }

          message.specialOrderTypes = reader.string();
          continue;
        }
        case 26: {
          if (tag !== 210) {
            break;
          }

          message.minFeeAmount = reader.string();
          continue;
        }
        case 27: {
          if (tag !== 216) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
        case 28: {
          if (tag !== 224) {
            break;
          }

          message.updatedAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarketMaker {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      organizationName: isSet(object.organizationName)
        ? globalThis.String(object.organizationName)
        : isSet(object.organization_name)
        ? globalThis.String(object.organization_name)
        : "",
      contactEmail: isSet(object.contactEmail)
        ? globalThis.String(object.contactEmail)
        : isSet(object.contact_email)
        ? globalThis.String(object.contact_email)
        : "",
      contactPhone: isSet(object.contactPhone)
        ? globalThis.String(object.contactPhone)
        : isSet(object.contact_phone)
        ? globalThis.String(object.contact_phone)
        : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      tier: isSet(object.tier) ? globalThis.String(object.tier) : "",
      marketsSupported: isSet(object.marketsSupported)
        ? globalThis.String(object.marketsSupported)
        : isSet(object.markets_supported)
        ? globalThis.String(object.markets_supported)
        : "",
      minQuoteSize: isSet(object.minQuoteSize)
        ? globalThis.Number(object.minQuoteSize)
        : isSet(object.min_quote_size)
        ? globalThis.Number(object.min_quote_size)
        : 0,
      maxQuoteSize: isSet(object.maxQuoteSize)
        ? globalThis.Number(object.maxQuoteSize)
        : isSet(object.max_quote_size)
        ? globalThis.Number(object.max_quote_size)
        : 0,
      spreadLimit: isSet(object.spreadLimit)
        ? globalThis.Number(object.spreadLimit)
        : isSet(object.spread_limit)
        ? globalThis.Number(object.spread_limit)
        : 0,
      quoteObligation: isSet(object.quoteObligation)
        ? globalThis.Boolean(object.quoteObligation)
        : isSet(object.quote_obligation)
        ? globalThis.Boolean(object.quote_obligation)
        : false,
      dailyVolumeTarget: isSet(object.dailyVolumeTarget)
        ? globalThis.Number(object.dailyVolumeTarget)
        : isSet(object.daily_volume_target)
        ? globalThis.Number(object.daily_volume_target)
        : 0,
      makerFee: isSet(object.makerFee)
        ? globalThis.Number(object.makerFee)
        : isSet(object.maker_fee)
        ? globalThis.Number(object.maker_fee)
        : 0,
      takerFee: isSet(object.takerFee)
        ? globalThis.Number(object.takerFee)
        : isSet(object.taker_fee)
        ? globalThis.Number(object.taker_fee)
        : 0,
      rebateRate: isSet(object.rebateRate)
        ? globalThis.Number(object.rebateRate)
        : isSet(object.rebate_rate)
        ? globalThis.Number(object.rebate_rate)
        : 0,
      rebateBalance: isSet(object.rebateBalance)
        ? globalThis.Number(object.rebateBalance)
        : isSet(object.rebate_balance)
        ? globalThis.Number(object.rebate_balance)
        : 0,
      apiAccess: isSet(object.apiAccess)
        ? globalThis.Boolean(object.apiAccess)
        : isSet(object.api_access)
        ? globalThis.Boolean(object.api_access)
        : false,
      maxOrdersPerSecond: isSet(object.maxOrdersPerSecond)
        ? globalThis.Number(object.maxOrdersPerSecond)
        : isSet(object.max_orders_per_second)
        ? globalThis.Number(object.max_orders_per_second)
        : 0,
      directMarketAccess: isSet(object.directMarketAccess)
        ? globalThis.Boolean(object.directMarketAccess)
        : isSet(object.direct_market_access)
        ? globalThis.Boolean(object.direct_market_access)
        : false,
      contractSignedAt: isSet(object.contractSignedAt)
        ? globalThis.String(object.contractSignedAt)
        : isSet(object.contract_signed_at)
        ? globalThis.String(object.contract_signed_at)
        : "0",
      obligationViolationCount: isSet(object.obligationViolationCount)
        ? globalThis.Number(object.obligationViolationCount)
        : isSet(object.obligation_violation_count)
        ? globalThis.Number(object.obligation_violation_count)
        : 0,
      auditLog: isSet(object.auditLog)
        ? globalThis.String(object.auditLog)
        : isSet(object.audit_log)
        ? globalThis.String(object.audit_log)
        : "",
      notesInternal: isSet(object.notesInternal)
        ? globalThis.String(object.notesInternal)
        : isSet(object.notes_internal)
        ? globalThis.String(object.notes_internal)
        : "",
      specialOrderTypes: isSet(object.specialOrderTypes)
        ? globalThis.String(object.specialOrderTypes)
        : isSet(object.special_order_types)
        ? globalThis.String(object.special_order_types)
        : "",
      minFeeAmount: isSet(object.minFeeAmount)
        ? globalThis.String(object.minFeeAmount)
        : isSet(object.min_fee_amount)
        ? globalThis.String(object.min_fee_amount)
        : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "0",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "0",
    };
  },

  toJSON(message: MarketMaker): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.organizationName !== undefined && message.organizationName !== "") {
      obj.organizationName = message.organizationName;
    }
    if (message.contactEmail !== undefined && message.contactEmail !== "") {
      obj.contactEmail = message.contactEmail;
    }
    if (message.contactPhone !== undefined && message.contactPhone !== "") {
      obj.contactPhone = message.contactPhone;
    }
    if (message.status !== undefined && message.status !== "") {
      obj.status = message.status;
    }
    if (message.tier !== undefined && message.tier !== "") {
      obj.tier = message.tier;
    }
    if (message.marketsSupported !== undefined && message.marketsSupported !== "") {
      obj.marketsSupported = message.marketsSupported;
    }
    if (message.minQuoteSize !== undefined && message.minQuoteSize !== 0) {
      obj.minQuoteSize = Math.round(message.minQuoteSize);
    }
    if (message.maxQuoteSize !== undefined && message.maxQuoteSize !== 0) {
      obj.maxQuoteSize = Math.round(message.maxQuoteSize);
    }
    if (message.spreadLimit !== undefined && message.spreadLimit !== 0) {
      obj.spreadLimit = Math.round(message.spreadLimit);
    }
    if (message.quoteObligation !== undefined && message.quoteObligation !== false) {
      obj.quoteObligation = message.quoteObligation;
    }
    if (message.dailyVolumeTarget !== undefined && message.dailyVolumeTarget !== 0) {
      obj.dailyVolumeTarget = Math.round(message.dailyVolumeTarget);
    }
    if (message.makerFee !== undefined && message.makerFee !== 0) {
      obj.makerFee = Math.round(message.makerFee);
    }
    if (message.takerFee !== undefined && message.takerFee !== 0) {
      obj.takerFee = Math.round(message.takerFee);
    }
    if (message.rebateRate !== undefined && message.rebateRate !== 0) {
      obj.rebateRate = Math.round(message.rebateRate);
    }
    if (message.rebateBalance !== undefined && message.rebateBalance !== 0) {
      obj.rebateBalance = Math.round(message.rebateBalance);
    }
    if (message.apiAccess !== undefined && message.apiAccess !== false) {
      obj.apiAccess = message.apiAccess;
    }
    if (message.maxOrdersPerSecond !== undefined && message.maxOrdersPerSecond !== 0) {
      obj.maxOrdersPerSecond = Math.round(message.maxOrdersPerSecond);
    }
    if (message.directMarketAccess !== undefined && message.directMarketAccess !== false) {
      obj.directMarketAccess = message.directMarketAccess;
    }
    if (message.contractSignedAt !== undefined && message.contractSignedAt !== "0") {
      obj.contractSignedAt = message.contractSignedAt;
    }
    if (message.obligationViolationCount !== undefined && message.obligationViolationCount !== 0) {
      obj.obligationViolationCount = Math.round(message.obligationViolationCount);
    }
    if (message.auditLog !== undefined && message.auditLog !== "") {
      obj.auditLog = message.auditLog;
    }
    if (message.notesInternal !== undefined && message.notesInternal !== "") {
      obj.notesInternal = message.notesInternal;
    }
    if (message.specialOrderTypes !== undefined && message.specialOrderTypes !== "") {
      obj.specialOrderTypes = message.specialOrderTypes;
    }
    if (message.minFeeAmount !== undefined && message.minFeeAmount !== "") {
      obj.minFeeAmount = message.minFeeAmount;
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarketMaker>, I>>(base?: I): MarketMaker {
    return MarketMaker.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarketMaker>, I>>(object: I): MarketMaker {
    const message = createBaseMarketMaker();
    message.id = object.id ?? "";
    message.tenantId = object.tenantId ?? "";
    message.organizationName = object.organizationName ?? "";
    message.contactEmail = object.contactEmail ?? "";
    message.contactPhone = object.contactPhone ?? "";
    message.status = object.status ?? "";
    message.tier = object.tier ?? "";
    message.marketsSupported = object.marketsSupported ?? "";
    message.minQuoteSize = object.minQuoteSize ?? 0;
    message.maxQuoteSize = object.maxQuoteSize ?? 0;
    message.spreadLimit = object.spreadLimit ?? 0;
    message.quoteObligation = object.quoteObligation ?? false;
    message.dailyVolumeTarget = object.dailyVolumeTarget ?? 0;
    message.makerFee = object.makerFee ?? 0;
    message.takerFee = object.takerFee ?? 0;
    message.rebateRate = object.rebateRate ?? 0;
    message.rebateBalance = object.rebateBalance ?? 0;
    message.apiAccess = object.apiAccess ?? false;
    message.maxOrdersPerSecond = object.maxOrdersPerSecond ?? 0;
    message.directMarketAccess = object.directMarketAccess ?? false;
    message.contractSignedAt = object.contractSignedAt ?? "0";
    message.obligationViolationCount = object.obligationViolationCount ?? 0;
    message.auditLog = object.auditLog ?? "";
    message.notesInternal = object.notesInternal ?? "";
    message.specialOrderTypes = object.specialOrderTypes ?? "";
    message.minFeeAmount = object.minFeeAmount ?? "";
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
