// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v5.29.3
// source: common/referral.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "common";

export interface Referral {
  id?: string | undefined;
  tenantId?: string | undefined;
  referrerUserId?: string | undefined;
  referredUserId?: string | undefined;
  referralCode?: string | undefined;
  source?: string | undefined;
  status?: string | undefined;
  rewardType?: string | undefined;
  rewardAmount?: string | undefined;
  rewardCurrency?: string | undefined;
  rewardedAt?:
    | string
    | undefined;
  /** JSON string */
  meta?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
}

function createBaseReferral(): Referral {
  return {
    id: "",
    tenantId: "",
    referrerUserId: "",
    referredUserId: "",
    referralCode: "",
    source: "",
    status: "",
    rewardType: "",
    rewardAmount: "",
    rewardCurrency: "",
    rewardedAt: "0",
    meta: "",
    createdAt: "0",
    updatedAt: "0",
  };
}

export const Referral: MessageFns<Referral> = {
  encode(message: Referral, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    if (message.referrerUserId !== undefined && message.referrerUserId !== "") {
      writer.uint32(26).string(message.referrerUserId);
    }
    if (message.referredUserId !== undefined && message.referredUserId !== "") {
      writer.uint32(34).string(message.referredUserId);
    }
    if (message.referralCode !== undefined && message.referralCode !== "") {
      writer.uint32(42).string(message.referralCode);
    }
    if (message.source !== undefined && message.source !== "") {
      writer.uint32(50).string(message.source);
    }
    if (message.status !== undefined && message.status !== "") {
      writer.uint32(58).string(message.status);
    }
    if (message.rewardType !== undefined && message.rewardType !== "") {
      writer.uint32(66).string(message.rewardType);
    }
    if (message.rewardAmount !== undefined && message.rewardAmount !== "") {
      writer.uint32(74).string(message.rewardAmount);
    }
    if (message.rewardCurrency !== undefined && message.rewardCurrency !== "") {
      writer.uint32(82).string(message.rewardCurrency);
    }
    if (message.rewardedAt !== undefined && message.rewardedAt !== "0") {
      writer.uint32(88).int64(message.rewardedAt);
    }
    if (message.meta !== undefined && message.meta !== "") {
      writer.uint32(98).string(message.meta);
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      writer.uint32(104).int64(message.createdAt);
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      writer.uint32(112).int64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Referral {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReferral();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.referrerUserId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.referredUserId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.referralCode = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.source = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.rewardType = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.rewardAmount = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.rewardCurrency = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.rewardedAt = reader.int64().toString();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.meta = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.updatedAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Referral {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      referrerUserId: isSet(object.referrerUserId)
        ? globalThis.String(object.referrerUserId)
        : isSet(object.referrer_user_id)
        ? globalThis.String(object.referrer_user_id)
        : "",
      referredUserId: isSet(object.referredUserId)
        ? globalThis.String(object.referredUserId)
        : isSet(object.referred_user_id)
        ? globalThis.String(object.referred_user_id)
        : "",
      referralCode: isSet(object.referralCode)
        ? globalThis.String(object.referralCode)
        : isSet(object.referral_code)
        ? globalThis.String(object.referral_code)
        : "",
      source: isSet(object.source) ? globalThis.String(object.source) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      rewardType: isSet(object.rewardType)
        ? globalThis.String(object.rewardType)
        : isSet(object.reward_type)
        ? globalThis.String(object.reward_type)
        : "",
      rewardAmount: isSet(object.rewardAmount)
        ? globalThis.String(object.rewardAmount)
        : isSet(object.reward_amount)
        ? globalThis.String(object.reward_amount)
        : "",
      rewardCurrency: isSet(object.rewardCurrency)
        ? globalThis.String(object.rewardCurrency)
        : isSet(object.reward_currency)
        ? globalThis.String(object.reward_currency)
        : "",
      rewardedAt: isSet(object.rewardedAt)
        ? globalThis.String(object.rewardedAt)
        : isSet(object.rewarded_at)
        ? globalThis.String(object.rewarded_at)
        : "0",
      meta: isSet(object.meta) ? globalThis.String(object.meta) : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "0",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "0",
    };
  },

  toJSON(message: Referral): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.referrerUserId !== undefined && message.referrerUserId !== "") {
      obj.referrerUserId = message.referrerUserId;
    }
    if (message.referredUserId !== undefined && message.referredUserId !== "") {
      obj.referredUserId = message.referredUserId;
    }
    if (message.referralCode !== undefined && message.referralCode !== "") {
      obj.referralCode = message.referralCode;
    }
    if (message.source !== undefined && message.source !== "") {
      obj.source = message.source;
    }
    if (message.status !== undefined && message.status !== "") {
      obj.status = message.status;
    }
    if (message.rewardType !== undefined && message.rewardType !== "") {
      obj.rewardType = message.rewardType;
    }
    if (message.rewardAmount !== undefined && message.rewardAmount !== "") {
      obj.rewardAmount = message.rewardAmount;
    }
    if (message.rewardCurrency !== undefined && message.rewardCurrency !== "") {
      obj.rewardCurrency = message.rewardCurrency;
    }
    if (message.rewardedAt !== undefined && message.rewardedAt !== "0") {
      obj.rewardedAt = message.rewardedAt;
    }
    if (message.meta !== undefined && message.meta !== "") {
      obj.meta = message.meta;
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Referral>, I>>(base?: I): Referral {
    return Referral.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Referral>, I>>(object: I): Referral {
    const message = createBaseReferral();
    message.id = object.id ?? "";
    message.tenantId = object.tenantId ?? "";
    message.referrerUserId = object.referrerUserId ?? "";
    message.referredUserId = object.referredUserId ?? "";
    message.referralCode = object.referralCode ?? "";
    message.source = object.source ?? "";
    message.status = object.status ?? "";
    message.rewardType = object.rewardType ?? "";
    message.rewardAmount = object.rewardAmount ?? "";
    message.rewardCurrency = object.rewardCurrency ?? "";
    message.rewardedAt = object.rewardedAt ?? "0";
    message.meta = object.meta ?? "";
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
