// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v5.29.3
// source: common/trade.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "common";

export interface Trade {
  id?: string | undefined;
  tenantId?: string | undefined;
  instrumentId?: string | undefined;
  buyOrderId?: string | undefined;
  sellOrderId?: string | undefined;
  price?: string | undefined;
  quantity?:
    | string
    | undefined;
  /** JSON string */
  meta?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
}

function createBaseTrade(): Trade {
  return {
    id: "",
    tenantId: "",
    instrumentId: "",
    buyOrderId: "",
    sellOrderId: "",
    price: "",
    quantity: "",
    meta: "",
    createdAt: "0",
    updatedAt: "0",
  };
}

export const Trade: MessageFns<Trade> = {
  encode(message: Trade, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    if (message.instrumentId !== undefined && message.instrumentId !== "") {
      writer.uint32(26).string(message.instrumentId);
    }
    if (message.buyOrderId !== undefined && message.buyOrderId !== "") {
      writer.uint32(34).string(message.buyOrderId);
    }
    if (message.sellOrderId !== undefined && message.sellOrderId !== "") {
      writer.uint32(42).string(message.sellOrderId);
    }
    if (message.price !== undefined && message.price !== "") {
      writer.uint32(50).string(message.price);
    }
    if (message.quantity !== undefined && message.quantity !== "") {
      writer.uint32(58).string(message.quantity);
    }
    if (message.meta !== undefined && message.meta !== "") {
      writer.uint32(66).string(message.meta);
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      writer.uint32(72).int64(message.createdAt);
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      writer.uint32(80).int64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Trade {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrade();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.instrumentId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.buyOrderId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sellOrderId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.price = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.quantity = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.meta = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.updatedAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Trade {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      instrumentId: isSet(object.instrumentId)
        ? globalThis.String(object.instrumentId)
        : isSet(object.instrument_id)
        ? globalThis.String(object.instrument_id)
        : "",
      buyOrderId: isSet(object.buyOrderId)
        ? globalThis.String(object.buyOrderId)
        : isSet(object.buy_order_id)
        ? globalThis.String(object.buy_order_id)
        : "",
      sellOrderId: isSet(object.sellOrderId)
        ? globalThis.String(object.sellOrderId)
        : isSet(object.sell_order_id)
        ? globalThis.String(object.sell_order_id)
        : "",
      price: isSet(object.price) ? globalThis.String(object.price) : "",
      quantity: isSet(object.quantity) ? globalThis.String(object.quantity) : "",
      meta: isSet(object.meta) ? globalThis.String(object.meta) : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "0",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "0",
    };
  },

  toJSON(message: Trade): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.instrumentId !== undefined && message.instrumentId !== "") {
      obj.instrumentId = message.instrumentId;
    }
    if (message.buyOrderId !== undefined && message.buyOrderId !== "") {
      obj.buyOrderId = message.buyOrderId;
    }
    if (message.sellOrderId !== undefined && message.sellOrderId !== "") {
      obj.sellOrderId = message.sellOrderId;
    }
    if (message.price !== undefined && message.price !== "") {
      obj.price = message.price;
    }
    if (message.quantity !== undefined && message.quantity !== "") {
      obj.quantity = message.quantity;
    }
    if (message.meta !== undefined && message.meta !== "") {
      obj.meta = message.meta;
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Trade>, I>>(base?: I): Trade {
    return Trade.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Trade>, I>>(object: I): Trade {
    const message = createBaseTrade();
    message.id = object.id ?? "";
    message.tenantId = object.tenantId ?? "";
    message.instrumentId = object.instrumentId ?? "";
    message.buyOrderId = object.buyOrderId ?? "";
    message.sellOrderId = object.sellOrderId ?? "";
    message.price = object.price ?? "";
    message.quantity = object.quantity ?? "";
    message.meta = object.meta ?? "";
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
