// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v5.29.3
// source: common/wallet.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "common";

export interface Wallet {
  id?: string | undefined;
  tenantId?: string | undefined;
  userId?: string | undefined;
  accountId?: string | undefined;
  assetId?:
    | string
    | undefined;
  /**
   * Balances are integers in the Prisma schema, likely representing smallest unit (sats/cents)
   * or they might be floats in practice but stored as Int? Let's assume double or string for proto to be safe,
   * but if the DB has Int, it might be limited. The user schema says `Int?`.
   * Wait, `Int` in Prisma is 32-bit usually unless `BigInt`.
   * Crypto exchanges usually need Decimal or BigInt.
   * I will use string to be safe and compatible with the other protos I defined which used string for precision.
   */
  available?: string | undefined;
  locked?: string | undefined;
  total?: string | undefined;
  version?: number | undefined;
  status?:
    | string
    | undefined;
  /** JSON string */
  meta?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
}

function createBaseWallet(): Wallet {
  return {
    id: "",
    tenantId: "",
    userId: "",
    accountId: "",
    assetId: "",
    available: "",
    locked: "",
    total: "",
    version: 0,
    status: "",
    meta: "",
    createdAt: "0",
    updatedAt: "0",
  };
}

export const Wallet: MessageFns<Wallet> = {
  encode(message: Wallet, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    if (message.userId !== undefined && message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.accountId !== undefined && message.accountId !== "") {
      writer.uint32(34).string(message.accountId);
    }
    if (message.assetId !== undefined && message.assetId !== "") {
      writer.uint32(42).string(message.assetId);
    }
    if (message.available !== undefined && message.available !== "") {
      writer.uint32(50).string(message.available);
    }
    if (message.locked !== undefined && message.locked !== "") {
      writer.uint32(58).string(message.locked);
    }
    if (message.total !== undefined && message.total !== "") {
      writer.uint32(66).string(message.total);
    }
    if (message.version !== undefined && message.version !== 0) {
      writer.uint32(72).int32(message.version);
    }
    if (message.status !== undefined && message.status !== "") {
      writer.uint32(82).string(message.status);
    }
    if (message.meta !== undefined && message.meta !== "") {
      writer.uint32(106).string(message.meta);
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      writer.uint32(88).int64(message.createdAt);
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      writer.uint32(96).int64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Wallet {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWallet();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.accountId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.assetId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.available = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.locked = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.total = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.version = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.meta = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.updatedAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Wallet {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      accountId: isSet(object.accountId)
        ? globalThis.String(object.accountId)
        : isSet(object.account_id)
        ? globalThis.String(object.account_id)
        : "",
      assetId: isSet(object.assetId)
        ? globalThis.String(object.assetId)
        : isSet(object.asset_id)
        ? globalThis.String(object.asset_id)
        : "",
      available: isSet(object.available) ? globalThis.String(object.available) : "",
      locked: isSet(object.locked) ? globalThis.String(object.locked) : "",
      total: isSet(object.total) ? globalThis.String(object.total) : "",
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      meta: isSet(object.meta) ? globalThis.String(object.meta) : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "0",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "0",
    };
  },

  toJSON(message: Wallet): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.userId !== undefined && message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.accountId !== undefined && message.accountId !== "") {
      obj.accountId = message.accountId;
    }
    if (message.assetId !== undefined && message.assetId !== "") {
      obj.assetId = message.assetId;
    }
    if (message.available !== undefined && message.available !== "") {
      obj.available = message.available;
    }
    if (message.locked !== undefined && message.locked !== "") {
      obj.locked = message.locked;
    }
    if (message.total !== undefined && message.total !== "") {
      obj.total = message.total;
    }
    if (message.version !== undefined && message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.status !== undefined && message.status !== "") {
      obj.status = message.status;
    }
    if (message.meta !== undefined && message.meta !== "") {
      obj.meta = message.meta;
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Wallet>, I>>(base?: I): Wallet {
    return Wallet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Wallet>, I>>(object: I): Wallet {
    const message = createBaseWallet();
    message.id = object.id ?? "";
    message.tenantId = object.tenantId ?? "";
    message.userId = object.userId ?? "";
    message.accountId = object.accountId ?? "";
    message.assetId = object.assetId ?? "";
    message.available = object.available ?? "";
    message.locked = object.locked ?? "";
    message.total = object.total ?? "";
    message.version = object.version ?? 0;
    message.status = object.status ?? "";
    message.meta = object.meta ?? "";
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
