// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v5.29.3
// source: common/withdrawal.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "common";

export interface Withdrawal {
  id?: string | undefined;
  tenantId?: string | undefined;
  accountId?: string | undefined;
  assetId?: string | undefined;
  walletId?: string | undefined;
  amount?: string | undefined;
  fee?: string | undefined;
  status?: string | undefined;
  destinationAddress?: string | undefined;
  destinationTag?: string | undefined;
  chain?: string | undefined;
  txHash?: string | undefined;
  failureReason?: string | undefined;
  requestedBy?: string | undefined;
  approvedBy?: string | undefined;
  requestedAt?: string | undefined;
  approvedAt?: string | undefined;
  broadcastAt?: string | undefined;
  confirmedAt?: string | undefined;
  confirmations?:
    | number
    | undefined;
  /** JSON string */
  meta?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
}

function createBaseWithdrawal(): Withdrawal {
  return {
    id: "",
    tenantId: "",
    accountId: "",
    assetId: "",
    walletId: "",
    amount: "",
    fee: "",
    status: "",
    destinationAddress: "",
    destinationTag: "",
    chain: "",
    txHash: "",
    failureReason: "",
    requestedBy: "",
    approvedBy: "",
    requestedAt: "0",
    approvedAt: "0",
    broadcastAt: "0",
    confirmedAt: "0",
    confirmations: 0,
    meta: "",
    createdAt: "0",
    updatedAt: "0",
  };
}

export const Withdrawal: MessageFns<Withdrawal> = {
  encode(message: Withdrawal, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    if (message.accountId !== undefined && message.accountId !== "") {
      writer.uint32(26).string(message.accountId);
    }
    if (message.assetId !== undefined && message.assetId !== "") {
      writer.uint32(34).string(message.assetId);
    }
    if (message.walletId !== undefined && message.walletId !== "") {
      writer.uint32(42).string(message.walletId);
    }
    if (message.amount !== undefined && message.amount !== "") {
      writer.uint32(50).string(message.amount);
    }
    if (message.fee !== undefined && message.fee !== "") {
      writer.uint32(58).string(message.fee);
    }
    if (message.status !== undefined && message.status !== "") {
      writer.uint32(66).string(message.status);
    }
    if (message.destinationAddress !== undefined && message.destinationAddress !== "") {
      writer.uint32(74).string(message.destinationAddress);
    }
    if (message.destinationTag !== undefined && message.destinationTag !== "") {
      writer.uint32(82).string(message.destinationTag);
    }
    if (message.chain !== undefined && message.chain !== "") {
      writer.uint32(90).string(message.chain);
    }
    if (message.txHash !== undefined && message.txHash !== "") {
      writer.uint32(98).string(message.txHash);
    }
    if (message.failureReason !== undefined && message.failureReason !== "") {
      writer.uint32(106).string(message.failureReason);
    }
    if (message.requestedBy !== undefined && message.requestedBy !== "") {
      writer.uint32(114).string(message.requestedBy);
    }
    if (message.approvedBy !== undefined && message.approvedBy !== "") {
      writer.uint32(122).string(message.approvedBy);
    }
    if (message.requestedAt !== undefined && message.requestedAt !== "0") {
      writer.uint32(128).int64(message.requestedAt);
    }
    if (message.approvedAt !== undefined && message.approvedAt !== "0") {
      writer.uint32(136).int64(message.approvedAt);
    }
    if (message.broadcastAt !== undefined && message.broadcastAt !== "0") {
      writer.uint32(144).int64(message.broadcastAt);
    }
    if (message.confirmedAt !== undefined && message.confirmedAt !== "0") {
      writer.uint32(152).int64(message.confirmedAt);
    }
    if (message.confirmations !== undefined && message.confirmations !== 0) {
      writer.uint32(160).int32(message.confirmations);
    }
    if (message.meta !== undefined && message.meta !== "") {
      writer.uint32(170).string(message.meta);
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      writer.uint32(176).int64(message.createdAt);
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      writer.uint32(184).int64(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Withdrawal {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWithdrawal();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.accountId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.assetId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.walletId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.fee = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.destinationAddress = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.destinationTag = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.chain = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.txHash = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.failureReason = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.requestedBy = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.approvedBy = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.requestedAt = reader.int64().toString();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.approvedAt = reader.int64().toString();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.broadcastAt = reader.int64().toString();
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.confirmedAt = reader.int64().toString();
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.confirmations = reader.int32();
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.meta = reader.string();
          continue;
        }
        case 22: {
          if (tag !== 176) {
            break;
          }

          message.createdAt = reader.int64().toString();
          continue;
        }
        case 23: {
          if (tag !== 184) {
            break;
          }

          message.updatedAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Withdrawal {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      accountId: isSet(object.accountId)
        ? globalThis.String(object.accountId)
        : isSet(object.account_id)
        ? globalThis.String(object.account_id)
        : "",
      assetId: isSet(object.assetId)
        ? globalThis.String(object.assetId)
        : isSet(object.asset_id)
        ? globalThis.String(object.asset_id)
        : "",
      walletId: isSet(object.walletId)
        ? globalThis.String(object.walletId)
        : isSet(object.wallet_id)
        ? globalThis.String(object.wallet_id)
        : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      fee: isSet(object.fee) ? globalThis.String(object.fee) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      destinationAddress: isSet(object.destinationAddress)
        ? globalThis.String(object.destinationAddress)
        : isSet(object.destination_address)
        ? globalThis.String(object.destination_address)
        : "",
      destinationTag: isSet(object.destinationTag)
        ? globalThis.String(object.destinationTag)
        : isSet(object.destination_tag)
        ? globalThis.String(object.destination_tag)
        : "",
      chain: isSet(object.chain) ? globalThis.String(object.chain) : "",
      txHash: isSet(object.txHash)
        ? globalThis.String(object.txHash)
        : isSet(object.tx_hash)
        ? globalThis.String(object.tx_hash)
        : "",
      failureReason: isSet(object.failureReason)
        ? globalThis.String(object.failureReason)
        : isSet(object.failure_reason)
        ? globalThis.String(object.failure_reason)
        : "",
      requestedBy: isSet(object.requestedBy)
        ? globalThis.String(object.requestedBy)
        : isSet(object.requested_by)
        ? globalThis.String(object.requested_by)
        : "",
      approvedBy: isSet(object.approvedBy)
        ? globalThis.String(object.approvedBy)
        : isSet(object.approved_by)
        ? globalThis.String(object.approved_by)
        : "",
      requestedAt: isSet(object.requestedAt)
        ? globalThis.String(object.requestedAt)
        : isSet(object.requested_at)
        ? globalThis.String(object.requested_at)
        : "0",
      approvedAt: isSet(object.approvedAt)
        ? globalThis.String(object.approvedAt)
        : isSet(object.approved_at)
        ? globalThis.String(object.approved_at)
        : "0",
      broadcastAt: isSet(object.broadcastAt)
        ? globalThis.String(object.broadcastAt)
        : isSet(object.broadcast_at)
        ? globalThis.String(object.broadcast_at)
        : "0",
      confirmedAt: isSet(object.confirmedAt)
        ? globalThis.String(object.confirmedAt)
        : isSet(object.confirmed_at)
        ? globalThis.String(object.confirmed_at)
        : "0",
      confirmations: isSet(object.confirmations) ? globalThis.Number(object.confirmations) : 0,
      meta: isSet(object.meta) ? globalThis.String(object.meta) : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "0",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "0",
    };
  },

  toJSON(message: Withdrawal): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    if (message.tenantId !== undefined && message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.accountId !== undefined && message.accountId !== "") {
      obj.accountId = message.accountId;
    }
    if (message.assetId !== undefined && message.assetId !== "") {
      obj.assetId = message.assetId;
    }
    if (message.walletId !== undefined && message.walletId !== "") {
      obj.walletId = message.walletId;
    }
    if (message.amount !== undefined && message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.fee !== undefined && message.fee !== "") {
      obj.fee = message.fee;
    }
    if (message.status !== undefined && message.status !== "") {
      obj.status = message.status;
    }
    if (message.destinationAddress !== undefined && message.destinationAddress !== "") {
      obj.destinationAddress = message.destinationAddress;
    }
    if (message.destinationTag !== undefined && message.destinationTag !== "") {
      obj.destinationTag = message.destinationTag;
    }
    if (message.chain !== undefined && message.chain !== "") {
      obj.chain = message.chain;
    }
    if (message.txHash !== undefined && message.txHash !== "") {
      obj.txHash = message.txHash;
    }
    if (message.failureReason !== undefined && message.failureReason !== "") {
      obj.failureReason = message.failureReason;
    }
    if (message.requestedBy !== undefined && message.requestedBy !== "") {
      obj.requestedBy = message.requestedBy;
    }
    if (message.approvedBy !== undefined && message.approvedBy !== "") {
      obj.approvedBy = message.approvedBy;
    }
    if (message.requestedAt !== undefined && message.requestedAt !== "0") {
      obj.requestedAt = message.requestedAt;
    }
    if (message.approvedAt !== undefined && message.approvedAt !== "0") {
      obj.approvedAt = message.approvedAt;
    }
    if (message.broadcastAt !== undefined && message.broadcastAt !== "0") {
      obj.broadcastAt = message.broadcastAt;
    }
    if (message.confirmedAt !== undefined && message.confirmedAt !== "0") {
      obj.confirmedAt = message.confirmedAt;
    }
    if (message.confirmations !== undefined && message.confirmations !== 0) {
      obj.confirmations = Math.round(message.confirmations);
    }
    if (message.meta !== undefined && message.meta !== "") {
      obj.meta = message.meta;
    }
    if (message.createdAt !== undefined && message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== undefined && message.updatedAt !== "0") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Withdrawal>, I>>(base?: I): Withdrawal {
    return Withdrawal.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Withdrawal>, I>>(object: I): Withdrawal {
    const message = createBaseWithdrawal();
    message.id = object.id ?? "";
    message.tenantId = object.tenantId ?? "";
    message.accountId = object.accountId ?? "";
    message.assetId = object.assetId ?? "";
    message.walletId = object.walletId ?? "";
    message.amount = object.amount ?? "";
    message.fee = object.fee ?? "";
    message.status = object.status ?? "";
    message.destinationAddress = object.destinationAddress ?? "";
    message.destinationTag = object.destinationTag ?? "";
    message.chain = object.chain ?? "";
    message.txHash = object.txHash ?? "";
    message.failureReason = object.failureReason ?? "";
    message.requestedBy = object.requestedBy ?? "";
    message.approvedBy = object.approvedBy ?? "";
    message.requestedAt = object.requestedAt ?? "0";
    message.approvedAt = object.approvedAt ?? "0";
    message.broadcastAt = object.broadcastAt ?? "0";
    message.confirmedAt = object.confirmedAt ?? "0";
    message.confirmations = object.confirmations ?? 0;
    message.meta = object.meta ?? "";
    message.createdAt = object.createdAt ?? "0";
    message.updatedAt = object.updatedAt ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
