// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: market/market.proto

package market

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MarketService_SubscribePrices_FullMethodName = "/market.MarketService/SubscribePrices"
	MarketService_GetLatestPrice_FullMethodName  = "/market.MarketService/GetLatestPrice"
)

// MarketServiceClient is the client API for MarketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketServiceClient interface {
	// Streams real-time price updates for a given symbol
	SubscribePrices(ctx context.Context, in *SubscribePricesRequest, opts ...grpc.CallOption) (MarketService_SubscribePricesClient, error)
	// Gets the latest snapshot for a symbol
	GetLatestPrice(ctx context.Context, in *GetLatestPriceRequest, opts ...grpc.CallOption) (*PriceUpdate, error)
}

type marketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketServiceClient(cc grpc.ClientConnInterface) MarketServiceClient {
	return &marketServiceClient{cc}
}

func (c *marketServiceClient) SubscribePrices(ctx context.Context, in *SubscribePricesRequest, opts ...grpc.CallOption) (MarketService_SubscribePricesClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarketService_ServiceDesc.Streams[0], MarketService_SubscribePrices_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &marketServiceSubscribePricesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarketService_SubscribePricesClient interface {
	Recv() (*PriceUpdate, error)
	grpc.ClientStream
}

type marketServiceSubscribePricesClient struct {
	grpc.ClientStream
}

func (x *marketServiceSubscribePricesClient) Recv() (*PriceUpdate, error) {
	m := new(PriceUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *marketServiceClient) GetLatestPrice(ctx context.Context, in *GetLatestPriceRequest, opts ...grpc.CallOption) (*PriceUpdate, error) {
	out := new(PriceUpdate)
	err := c.cc.Invoke(ctx, MarketService_GetLatestPrice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServiceServer is the server API for MarketService service.
// All implementations must embed UnimplementedMarketServiceServer
// for forward compatibility
type MarketServiceServer interface {
	// Streams real-time price updates for a given symbol
	SubscribePrices(*SubscribePricesRequest, MarketService_SubscribePricesServer) error
	// Gets the latest snapshot for a symbol
	GetLatestPrice(context.Context, *GetLatestPriceRequest) (*PriceUpdate, error)
	mustEmbedUnimplementedMarketServiceServer()
}

// UnimplementedMarketServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMarketServiceServer struct {
}

func (UnimplementedMarketServiceServer) SubscribePrices(*SubscribePricesRequest, MarketService_SubscribePricesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribePrices not implemented")
}
func (UnimplementedMarketServiceServer) GetLatestPrice(context.Context, *GetLatestPriceRequest) (*PriceUpdate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestPrice not implemented")
}
func (UnimplementedMarketServiceServer) mustEmbedUnimplementedMarketServiceServer() {}

// UnsafeMarketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketServiceServer will
// result in compilation errors.
type UnsafeMarketServiceServer interface {
	mustEmbedUnimplementedMarketServiceServer()
}

func RegisterMarketServiceServer(s grpc.ServiceRegistrar, srv MarketServiceServer) {
	s.RegisterService(&MarketService_ServiceDesc, srv)
}

func _MarketService_SubscribePrices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribePricesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketServiceServer).SubscribePrices(m, &marketServiceSubscribePricesServer{stream})
}

type MarketService_SubscribePricesServer interface {
	Send(*PriceUpdate) error
	grpc.ServerStream
}

type marketServiceSubscribePricesServer struct {
	grpc.ServerStream
}

func (x *marketServiceSubscribePricesServer) Send(m *PriceUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _MarketService_GetLatestPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServiceServer).GetLatestPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketService_GetLatestPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServiceServer).GetLatestPrice(ctx, req.(*GetLatestPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketService_ServiceDesc is the grpc.ServiceDesc for MarketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "market.MarketService",
	HandlerType: (*MarketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestPrice",
			Handler:    _MarketService_GetLatestPrice_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribePrices",
			Handler:       _MarketService_SubscribePrices_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "market/market.proto",
}
