FROM node:20-bookworm

RUN apt-get update && \
    apt-get install -y python3 make g++ cmake && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json package-lock.json ./
COPY src/prisma/schema.prisma ./src/prisma/schema.prisma

RUN npm ci

COPY . .

EXPOSE 3000

CMD npx prisma generate && npm run dev
